import { useState, useEffect, createContext, useContext } from 'react';
import { NavLink, Outlet, useParams, Navigate, Link, useLocation } from 'react-router-dom';
import { Sun, Users, CalendarDays, LayoutDashboard, Settings, Plug, ClipboardList, Sprout, MessageSquare, MoreHorizontal, LogOut, ArrowUpRight, Menu, X, ShieldCheck, Bell, BookOpen, ListChecks, Image } from 'lucide-react';
import { Brand } from './PublicLayout';
import { useAuth } from '../lib/context';
import { api, errorText, dateLabel } from '../lib/api';
import { toast } from 'sonner';

const WorkspaceContext=createContext(null);
export const useWorkspace=()=>useContext(WorkspaceContext);
const navigation={parent:[['today','Today',Sun],['child','My child',Users],['schedule','Schedule',CalendarDays],['activities','Home activities',Sprout],['updates','Classroom updates',MessageSquare],['more','More',MoreHorizontal]],staff:[['today','Today',Sun],['children','Children',Users],['classes','Classes',BookOpen],['more','More',MoreHorizontal]],admin:[['overview','Overview',LayoutDashboard],['enquiries','Enquiries & admissions',ClipboardList],['children','Children',Users],['schedule','Schedule',CalendarDays],['integrations','Integrations',Plug],['settings','Settings',Settings],['media','Site images',Image],['audit','Audit trail',ShieldCheck],['checklist','Project checklist',ListChecks]]};
export const PortalLayout=()=>{
 const {role}=useParams(),{user,loading,logout}=useAuth(),location=useLocation();
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[mobile,setMobile]=useState(false);
 const refresh=async()=>{setError('');try{const res=await api.get(`/workspace/${role}`);setData(res.data);}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 useEffect(()=>{if(user&&user.roles.includes(role)){setBusy(true);refresh();} /* role data is isolated server-side */},[role,user?.id]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>setMobile(false),[location.pathname]);
 if(loading)return <div className="loading-screen" role="status" data-testid="auth-loading">Opening your workspace…</div>;
 if(!user)return <Navigate to="/login" replace/>;
 if(!navigation[role]||!user.roles.includes(role))return <div className="container section-pad"><h1 data-testid="permission-denied">This workspace isn’t available to your account.</h1><p>Changing a page address does not change your permissions.</p><Link to={`/portal/${user.role}/${user.role==='admin'?'overview':'today'}`} data-testid="permission-return">Return to your workspace</Link></div>;
 const signOut=async()=>{try{await logout();}catch(e){toast.error(errorText(e));}};
 const current=navigation[role].find(n=>location.pathname.endsWith('/'+n[0]));
 return <WorkspaceContext.Provider value={{data,refresh,role,user}}><div className="portal-shell"><aside className={`sidebar ${mobile?'sidebar-open':''}`}><Brand/><span className="workspace-label">{role==='parent'?'PARENT PORTAL':role==='staff'?'CARE TEAM WORKSPACE':'ADMINISTRATION'}</span><nav aria-label="Workspace navigation">{navigation[role].map(([to,label,Icon])=><NavLink to={`/portal/${role}/${to}`} key={to} data-testid={`sidebar-${to}`}><Icon size={19}/>{label}{to==='enquiries'&&data?.enquiries?.length>0&&<span className="nav-count">{data.enquiries.length}</span>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="sidebar-help"><Sprout size={25}/><strong>A little support goes a long way.</strong><Link to="/contact" data-testid="portal-contact-support">Contact the center<ArrowUpRight size={15}/></Link></div><Link to="/" data-testid="portal-view-website"><ArrowUpRight size={18}/> View website</Link><button data-testid="portal-sign-out" onClick={signOut}><LogOut size={18}/> Sign out</button></div></aside>{mobile&&<button className="sidebar-backdrop" aria-label="Close menu" data-testid="sidebar-backdrop" onClick={()=>setMobile(false)}/>}
 <div className="portal-body"><header className="portal-topbar"><div><button className="icon-button portal-mobile-menu" aria-label="Toggle workspace navigation" onClick={()=>setMobile(!mobile)} data-testid="portal-menu-toggle">{mobile?<X/>:<Menu/>}</button><span>My workspace</span><span className="slash">/</span><strong data-testid="portal-page-label">{current?.[1]||'Workspace'}</strong></div><div><span className="portal-center-label"><span className="presence-dot"/> Gurugram · Sector 37C</span><Link to={`/portal/${role}/${role==='admin'?'enquiries':'more'}`} className="icon-button" aria-label="Workspace updates" data-testid="portal-notifications"><Bell size={19}/></Link><div className="user-avatar" data-testid="portal-user-avatar">{role==='parent'?'AF':role==='staff'?'CT':'AD'}</div></div></header><div className="demo-banner"><span data-testid="portal-demo-notice"><ShieldCheck size={15}/><strong>Demonstration workspace</strong> <span>· Fictional data only. No live care, payments or notifications.</span></span><Link to="/login" data-testid="change-demo-persona">Change demo persona <ArrowUpRight size={14}/></Link></div><main className="portal-content" id="main-content">{busy?<div className="loading-screen" role="status" data-testid="workspace-loading">Getting your day ready…</div>:error?<div className="error-state" role="alert" data-testid="workspace-error"><h2>We couldn’t load your workspace.</h2><p>{error}</p><button className="button primary" onClick={refresh} data-testid="workspace-retry">Try again</button></div>:<Outlet/>}</main><footer className="portal-footer"><span>Moonlight Neurocare · A shared circle of support</span><span>Center time: Asia/Kolkata (IST)</span></footer></div>{role!=='admin'&&<nav className="portal-bottom-nav" aria-label="Mobile workspace navigation">{navigation[role].filter(([key])=>role==='parent'?['today','child','schedule','more'].includes(key):true).map(([to,label,Icon])=><NavLink to={`/portal/${role}/${to}`} data-testid={`mobile-tab-${to}`} key={to}><Icon size={20}/><span>{label}</span></NavLink>)}</nav>}</div></WorkspaceContext.Provider>;
};
export const PortalHeading=({eyebrow,title,subtitle,action})=><div className="portal-heading"><div><span className="eyebrow" data-testid="portal-heading-eyebrow">{eyebrow||dateLabel(new Date())}</span><h1 data-testid="portal-heading-title">{title}</h1>{subtitle&&<p data-testid="portal-heading-subtitle">{subtitle}</p>}</div>{action}</div>;
export const EmptyState=({icon:Icon=ClipboardList,title,description,id='empty-state',action})=><div className="empty-state" data-testid={id}><Icon size={32} strokeWidth={1.4}/><h2>{title}</h2><p>{description}</p>{action}</div>;