import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowUpRight, Heart, MessageCircle, ClipboardList, Sprout, CalendarCheck, ShieldCheck, Award, Sparkles, UserRound, GraduationCap } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from './ui/accordion';
import { services, sports, faqs, SPORTS_HERO, DIRECTOR_PHOTO, CENTER_IMAGES, DIRECTOR_QUALS, TEAM_DEFAULTS } from '../lib/content';
import { useOrganization, useBooking } from '../lib/context';
import { mediaUrl } from '../lib/api';

const EASE = [0.22, 1, 0.36, 1];
export const Reveal = ({children, delay=0, y=26, className, as='div', ...rest}) => {
  const M = motion[as] || motion.div;
  return <M initial={{opacity:0, y}} whileInView={{opacity:1, y:0}} viewport={{once:true, margin:'-70px'}} transition={{duration:.6, delay, ease:EASE}} className={className} {...rest}>{children}</M>;
};

export const SectionHeading = ({eyebrow,title,description,link,id='section'}) => <div className="section-heading"><div><span className="eyebrow" data-testid={`${id}-eyebrow`}>{eyebrow}</span><h2 className="section-title" data-testid={`${id}-title`}>{title}</h2>{description&&<p data-testid={`${id}-description`}>{description}</p>}</div>{link&&<Link to={link.to} className="text-link" data-testid={`${id}-link`}>{link.label}<ArrowUpRight size={18}/></Link>}</div>;
export const ServiceGrid = ({items=services}) => {
  const {organization} = useOrganization() || {};
  const overrides = organization?.therapy_images || {};
  return <div className="service-grid">{items.map(({slug,title,icon:Icon,color,short,image},i)=>{const photo=overrides[slug]?mediaUrl(overrides[slug]):image;return <motion.div key={slug} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:.5,delay:Math.min(i*0.05,0.3),ease:EASE}}><Link className="service-card" to={`/therapies/${slug}`} data-testid={`service-${slug}`}>{photo&&<span className="service-photo"><img src={photo} alt={title} loading="lazy"/></span>}<span className={`service-icon ${color}`}><Icon size={26} strokeWidth={1.5}/></span><h3>{title}</h3><p>{short}</p><span className="service-card-bottom">Explore therapy <ArrowUpRight size={18}/></span></Link></motion.div>;})}</div>;
};
export const SportsGrid = ({items=sports}) => <div className="sports-grid">{items.map(({slug,title,icon:Icon,color,image,short,focus},i)=><motion.div key={slug} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:.55,delay:Math.min(i*0.06,0.36),ease:EASE}} whileHover={{y:-6}}><Link className="sport-card" to={`/sports/${slug}`} data-testid={`sport-${slug}`}><div className="sport-card-media"><img src={image} alt={`${title} at Moonlight Neurocare`} loading="lazy"/><span className={`sport-icon ${color}`}><Icon size={20} strokeWidth={1.6}/></span></div><div className="sport-card-body"><h3>{title}</h3><p>{short}</p><span className="sport-card-focus">{focus}</span><span className="sport-card-link">Explore <ArrowUpRight size={16}/></span></div></Link></motion.div>)}</div>;
export const SportsShowcase = () => <section className="sports-section section-pad"><div className="container">
  <Reveal><SectionHeading id="sports" eyebrow="NEW · PLAYFUL MOVEMENT" title="Indoor sports, built around every child." description="Skating, climbing, balance and ball play — gentle, sensory-friendly movement that builds confidence, coordination and connection, at your child’s pace." link={{to:'/sports',label:'All sports'}}/></Reveal>
  <div className="sports-feature"><Reveal className="sports-feature-media" y={30}><img className="kenburns" src={SPORTS_HERO} alt="Children moving and playing in a warm, sensory-friendly indoor studio" loading="lazy"/></Reveal><Reveal className="sports-feature-copy" delay={0.1}><span className="eyebrow">MOVEMENT WITH MEANING</span><h3>Sport, the sensory-friendly way.</h3><p>Every activity is calm, unhurried and adaptable. There’s always space to watch first, take a break, or try a different way — because confidence grows when a child feels safe.</p><ul className="check-list"><li><ShieldCheck size={17}/> Soft equipment and safe, padded spaces</li><li><Heart size={17}/> Led by your child’s comfort and pace</li><li><Sprout size={17}/> Building motor skills, focus and connection</li></ul></Reveal></div>
  <SportsGrid/>
</div></section>;
export const GettingStarted = () => <section className="process-section section-pad"><div className="container"><Reveal><SectionHeading id="getting-started" eyebrow="A GENTLE FIRST STEP" title="You don’t have to figure it out alone." description="We begin with listening. The next steps are a conversation, not a commitment."/></Reveal>
  <div className="process-grid">{[[MessageCircle,'01','Let’s talk','Tell us what’s on your mind and what matters to your family.'],[ClipboardList,'02','Understand your child','Discuss an individual assessment and your child’s preferences.'],[Sprout,'03','Agree on a plan','Set meaningful goals together, with space for your questions.'],[CalendarCheck,'04','Grow, reflect, adjust','Make room for sessions, family involvement and regular reviews.']].map(([Icon,n,t,d],i)=><motion.div className="process-step" key={n} data-testid={`process-step-${n}`} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:.5,delay:Math.min(i*0.07,0.35),ease:EASE}}><div className="step-top"><Icon size={28} strokeWidth={1.5}/><span>{n}</span></div><h3>{t}</h3><p>{d}</p></motion.div>)}</div><Link className="text-link" to="/what-to-expect" data-testid="process-what-to-expect">What to expect on your first visit <ArrowUpRight size={17}/></Link></div></section>;
export const FAQSection = () => <section className="section-pad"><div className="container faq-grid"><div><span className="eyebrow">A FEW THINGS YOU MAY BE WONDERING</span><h2 className="section-title" data-testid="faq-title">Questions are always welcome.</h2><p>Every family starts somewhere different.<br/>We’re here to help you find your next step.</p><Link to="/contact" className="text-link" data-testid="faq-contact">Let’s talk <ArrowUpRight size={17}/></Link></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger data-testid={`faq-question-${i}`}>{q}</AccordionTrigger><AccordionContent data-testid={`faq-answer-${i}`}>{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>;
export const FinalCTA = () => { const {openBooking}=useBooking(); return <section className="final-cta"><div className="container"><Reveal><div><span className="eyebrow">WHEN YOU’RE READY, WE’RE HERE</span><h2 data-testid="final-cta-title">Small steps. Shared possibilities.</h2><p>A conversation is a good place to begin.</p></div></Reveal><button onClick={openBooking} className="button light-button" data-testid="final-book-assessment">Book an assessment <ArrowUpRight size={18}/></button></div></section>; };
export const CarePrinciples = () => <div className="care-principles container">{[[Heart,'Your child, at the center','Individual needs. Meaningful goals.'],[MessageCircle,'Your family, part of the team','Listening, sharing and planning together.'],[ShieldCheck,'Care that respects every child','Every voice. Every way of communicating.']].map(([Icon,title,copy],i)=><motion.div key={title} data-testid={`care-principle-${i}`} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-40px'}} transition={{duration:.5,delay:i*0.08,ease:EASE}}><Icon size={28} strokeWidth={1.4}/><div><strong>{title}</strong><p>{copy}</p></div></motion.div>)}</div>;
export const DirectorSection = () => { const {organization:org}=useOrganization(); const photo=org?.director_photo?mediaUrl(org.director_photo):DIRECTOR_PHOTO; return <section className="director-section section-pad"><div className="container director-grid">
  <Reveal className="director-media" y={30}>
    <div className="director-photo"><img src={photo} alt="Dr. Dharamveer (PT), Director and Pediatric Therapist at Moonlight Neurocare" loading="lazy"/></div>
    <div className="director-badge" data-testid="director-experience"><span className="director-badge-num">5+</span><span>years in pediatric therapy</span></div>
  </Reveal>
  <Reveal className="director-copy" delay={0.1}>
    <span className="eyebrow">MEET THE DIRECTOR</span>
    <h2 className="section-title" data-testid="director-name">Dr. Dharamveer <span>(PT)</span></h2>
    <span className="director-role" data-testid="director-role"><Award size={16}/> Director & Pediatric Therapist · Moonlight Neurocare, Gurugram</span>
    <ul className="director-quals" data-testid="director-qualifications">{DIRECTOR_QUALS.map(q=><li key={q}><GraduationCap size={15} strokeWidth={1.7}/> {q}</li>)}</ul>
    <p data-testid="director-bio">A child-centred, evidence-based pediatric therapist devoted to helping every child grow — at their own pace, and in their own way. With over five years of hands-on experience, Dr. Dharamveer supports children with sensory processing difficulties, developmental delays, behavioural and communication concerns, and challenges with everyday activities and participation.</p>
    <p>Through structured therapy, meaningful play and family-centred guidance, he helps children build independence, confidence and functional skills — keeping families closely involved and supported at every step of the journey. As Director, he leads a warm, professional and child-friendly space where progress is measured in each child’s own milestones.</p>
    <div className="director-focus">{['Sensory processing','Developmental delays','Behavioural support','Communication','Daily-living skills'].map(t=><span key={t} data-testid={`director-focus-${t.split(' ')[0].toLowerCase()}`}>{t}</span>)}</div>
    <div className="director-quote" data-testid="director-tagline"><Sparkles size={20} strokeWidth={1.6}/> Where every child shines.</div>
  </Reveal>
</div></section>; };
export const CenterGallery = () => <section className="center-gallery section-pad"><div className="container">
  <Reveal><SectionHeading id="center" eyebrow="A REAL PLACE, IN GURUGRAM" title="Step inside our center." description="A calm, purpose-built space in Sector 37C — bright sensory-therapy rooms, soft, safe equipment and plenty of room to move, play and feel at ease."/></Reveal>
  <div className="center-gallery-grid">
    <Reveal className="cg-item cg-wide" y={26}><img src={CENTER_IMAGES.exterior} alt="Moonlight Neurocare center building in Sector 37C, Gurugram" loading="lazy"/><span className="cg-caption">Our building · Sector 37C, Gurugram</span></Reveal>
    <Reveal className="cg-item cg-wide" y={26} delay={0.05}><img src={CENTER_IMAGES.gym} alt="Bright indoor sensory movement gym with swings, trampoline and soft play" loading="lazy"/><span className="cg-caption">The movement & sensory gym</span></Reveal>
    <Reveal className="cg-item" y={26} delay={0.1}><img src={CENTER_IMAGES.swings} alt="Occupational therapy sensory room with suspension swings and rope ladder" loading="lazy"/><span className="cg-caption">Sensory integration room</span></Reveal>
    <Reveal className="cg-item" y={26} delay={0.15}><img src={CENTER_IMAGES.room} alt="Calm therapy room with soft mats and sensory swings" loading="lazy"/><span className="cg-caption">A quiet therapy space</span></Reveal>
  </div>
</div></section>;
export const TeamSection = () => {
  const {organization:org} = useOrganization();
  const team = org?.team || [];
  const teamPhoto = org?.team_photo ? mediaUrl(org.team_photo) : '';
  return <section className="team-section section-pad"><div className="container">
  <Reveal><SectionHeading id="team" eyebrow="THE TEAM BEHIND THE CARE" title="A growing team, chosen with care." description="Every therapist who joins Moonlight is chosen for both skill and heart. As our team grows, their profiles appear here."/></Reveal>
  {teamPhoto && <Reveal className="team-photo" y={26}><img src={teamPhoto} alt="The Moonlight Neurocare team and center" loading="lazy"/></Reveal>}
  <div className="team-grid">{team.length ? team.map((m,i)=><motion.div className="team-card" key={m.id} data-testid={`team-member-${i}`} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:.5,delay:Math.min(i*0.06,0.3),ease:EASE}}>{m.photo?<span className="team-avatar team-avatar-photo"><img src={mediaUrl(m.photo)} alt={m.name}/></span>:<span className="team-avatar"><UserRound size={26} strokeWidth={1.5}/></span>}<h3>{m.name}</h3><span className="team-member-role">{m.role}</span></motion.div>) : TEAM_DEFAULTS.map((m,i)=><motion.div className="team-card team-card-default" key={m.id} data-testid={`team-role-${i}`} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:.5,delay:Math.min(i*0.06,0.3),ease:EASE}}><span className="team-avatar"><UserRound size={26} strokeWidth={1.5}/></span><h3>{m.name}</h3><span className="team-member-role">{m.role}</span><p className="team-bio">{m.bio}</p><span className="team-focus">{m.focus}</span><span className="status sage">Profile pending verification</span></motion.div>)}</div>
  <Reveal className="team-note"><div><strong>Are you a qualified pediatric therapist?</strong><p>We’d love to hear from thoughtful, child-first professionals who want to grow with us.</p></div><Link to="/contact" className="button primary" data-testid="team-join">Get in touch <ArrowUpRight size={17}/></Link></Reveal>
</div></section>; };