import { useState } from 'react';
import { CalendarDays, Clock, MapPin, ArrowUpRight, Check, X } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Button } from './ui/button';
import { api, errorText, dateLabel, timeLabel } from '../lib/api';
import { useWorkspace, EmptyState } from './PortalLayout';
import { toast } from 'sonner';

export const SessionList=({sessions,compact=false})=>{
 const {role,refresh,data}=useWorkspace();
 const [selected,setSelected]=useState(null),[kind,setKind]=useState('Reschedule'),[date,setDate]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await api.post('/appointment-requests',{appointment_id:selected.id,kind,preferred_date:date,reason});setSelected(null);setDate('');setReason('');toast.success('Your request is pending review. The appointment has not changed.');await refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const mark=async(session,attendance)=>{setBusy(true);try{await api.patch(`/appointments/${session.id}/attendance`,{attendance,version:session.version});toast.success('Session attendance saved. No package credits were changed.');await refresh();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 return <>{!sessions.length?<EmptyState icon={CalendarDays} title="No sessions in this view" description="Confirmed sessions will appear here." id="sessions-empty"/>:<div className={`session-list ${compact?'compact':''}`}>{sessions.map((session,i)=>{const pending=data.requests?.some(r=>r.appointment_id===session.id&&r.status==='Pending');return <article className="session-row" key={session.id} data-testid={`session-${session.id}`}><div className={`session-time ${i%2?'peach':'sage'}`}><strong>{timeLabel(session.starts_at)}</strong><span>{dateLabel(session.starts_at)}</span></div><div className="session-info"><div className="session-info-top"><h3>{session.service}</h3><span className={`status ${pending?'yellow':'sage'}`} data-testid={`session-status-${session.id}`}>{pending?'Change pending':session.status}</span></div>{role!=='parent'&&<strong className="session-child-name">{session.child_name}</strong>}<p><Clock size={13}/>{session.duration_minutes} min <span>·</span> {session.staff_label}</p><p><MapPin size={13}/>{session.room} <span>·</span> {session.mode}</p></div>{role==='parent'&&<button className="session-action" disabled={pending} onClick={()=>{setError('');setSelected(session);}} data-testid={`request-change-${session.id}`}>{pending?'Pending review':'Request a change'}{!pending&&<ArrowUpRight size={15}/>}</button>}{role==='staff'&&<div className="attendance-actions"><span className="small" data-testid={`attendance-state-${session.id}`}>{session.attendance}</span><button title="Confirm present" aria-label={`Confirm ${session.child_name} present`} data-testid={`mark-present-${session.id}`} disabled={busy||session.attendance==='Present'} onClick={()=>mark(session,'Present')} className="icon-button attendance-present"><Check size={18}/></button><button title="Mark absent" aria-label={`Mark ${session.child_name} absent`} data-testid={`mark-absent-${session.id}`} disabled={busy||session.attendance==='Absent'} onClick={()=>mark(session,'Absent')} className="icon-button"><X size={18}/></button></div>}</article>;})}</div>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent data-testid="appointment-request-dialog"><DialogHeader><DialogTitle>Let’s find a better fit.</DialogTitle><DialogDescription>{selected?.service} · {selected&&dateLabel(selected.starts_at)}. A request is not a confirmed change.</DialogDescription></DialogHeader><form onSubmit={submit}><div className="field"><label htmlFor="request-kind">Request type</label><select id="request-kind" data-testid="request-kind" value={kind} onChange={e=>setKind(e.target.value)}><option>Reschedule</option><option>Absence</option></select></div>{kind==='Reschedule'&&<div className="field"><label htmlFor="preferred-date">Preferred date</label><input id="preferred-date" data-testid="request-preferred-date" type="date" value={date} min={new Date().toLocaleDateString('en-CA')} onChange={e=>setDate(e.target.value)} required/></div>}<div className="field"><label htmlFor="request-reason">A short note for the team</label><textarea id="request-reason" data-testid="request-reason" value={reason} onChange={e=>setReason(e.target.value)} required minLength={2} maxLength={500} placeholder="Please avoid sensitive clinical details."/></div><p className="small muted" data-testid="cancellation-policy-notice">Cancellation fees and notice periods are awaiting center approval. This demo does not cancel the session or charge a fee.</p>{error&&<p className="error-message" role="alert" data-testid="appointment-request-error">{error}</p>}<Button data-testid="submit-appointment-request" className="button primary full-width" disabled={busy}>{busy?'Saving…':'Send request for review'}<ArrowUpRight size={16}/></Button></form></DialogContent></Dialog></>;
};