import { useState } from 'react';
import { CalendarDays, Clock, Play, Sparkles, UserRound, Video } from 'lucide-react';
import { useWorkspace, PortalHeading, EmptyState } from '../PortalLayout';
import { dateLabel } from '../../lib/api';
import { PracticeVideoPlayer } from './PracticeVideoPlayer';
import { PracticeHubTabs } from './PracticeHubTabs';
import { ParentWeeklyPlans } from './WeeklyPlansParent';

const durationLabel=seconds=>`${Math.max(1,Math.ceil((seconds||0)/60))} min`;

const ParentVideoGuides=()=>{
 const {data,refresh}=useWorkspace(),[selected,setSelected]=useState(null),[filter,setFilter]=useState('All');
 const videos=data.practice_videos||[],shown=filter==='New'?videos.filter(video=>!video.viewed):videos;
 return <><div className="filter-bar"><button className={filter==='All'?'filter active':'filter'} aria-pressed={filter==='All'} onClick={()=>setFilter('All')} data-testid="practice-filter-all">All guides</button><button className={filter==='New'?'filter active':'filter'} aria-pressed={filter==='New'} onClick={()=>setFilter('New')} data-testid="practice-filter-new">New for you {data.video_unread>0&&`(${data.video_unread})`}</button></div>{shown.length?<div className="practice-grid" data-testid="parent-practice-list">{shown.map(video=><article className={`practice-card ${!video.viewed?'unread':''}`} key={video.id} data-testid={`parent-practice-card-${video.id}`}><button className="practice-cover" onClick={()=>setSelected(video)} aria-label={`Play ${video.title}`} data-testid={`play-practice-${video.id}`}><span className="practice-play"><Play fill="currentColor"/></span><span>{video.therapy}</span>{!video.viewed&&<strong data-testid={`practice-new-badge-${video.id}`}>New</strong>}</button><div className="practice-card-body"><div className="practice-meta-row"><span data-testid={`practice-date-${video.id}`}><CalendarDays/> {dateLabel(`${video.session_date}T12:00:00+05:30`)}</span><span data-testid={`practice-duration-${video.id}`}><Clock/> {durationLabel(video.duration_seconds)}</span></div><h2 data-testid={`practice-title-${video.id}`}>{video.title}</h2><p data-testid={`practice-note-${video.id}`}>{video.note}</p><div className="practice-byline"><UserRound/><span>Shared by {video.therapist_name}</span></div><button className="text-link" onClick={()=>setSelected(video)} data-testid={`open-practice-${video.id}`}>Watch the guide <Play size={14}/></button></div></article>)}</div>:<EmptyState icon={Video} id="practice-videos-empty" title={filter==='New'?'You’re all caught up':'No home-practice videos yet'} description={filter==='New'?'Any new guide from the care team will appear here.':'After a session, your therapist can share a short video with simple steps to practise at home.'}/>}<PracticeVideoPlayer video={selected} open={!!selected} onOpenChange={open=>!open&&setSelected(null)} markViewed onViewed={refresh}/></>;
};

export const ParentPracticePage=()=>{const {data}=useWorkspace(),[tab,setTab]=useState('plans');return <><PortalHeading eyebrow="A FEW CLEAR STEPS FOR HOME" title="Practice together, one small step at a time." subtitle="Weekly notes and short guides shared privately by your child’s care team." action={data.practice_unread>0&&<span className="practice-heading-alert" data-testid="practice-page-unread"><Sparkles size={16}/>{data.practice_unread} new</span>}/><PracticeHubTabs active={tab} onChange={setTab} planUnread={data.plan_unread} videoUnread={data.video_unread}/>{tab==='plans'?<ParentWeeklyPlans/>:<ParentVideoGuides/>}</>;};