import { useEffect, useState } from 'react';
import { CalendarDays, Clock, UserRound } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';
import { api, dateLabel, errorText } from '../../lib/api';

const durationLabel=seconds=>`${Math.max(1,Math.ceil((seconds||0)/60))} min guide`;

export const PracticeVideoPlayer=({video,open,onOpenChange,markViewed=false,onViewed})=>{
 const [source,setSource]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open||!video)return;let active=true,url='';setLoading(true);setError('');api.get(`/practice-videos/${video.id}/media`,{responseType:'blob'}).then(res=>{if(!active)return;url=URL.createObjectURL(res.data);setSource(url);if(markViewed&&!video.viewed)api.post(`/practice-videos/${video.id}/viewed`).then(()=>onViewed?.()).catch(()=>{});}).catch(err=>active&&setError(errorText(err))).finally(()=>active&&setLoading(false));return()=>{active=false;if(url)URL.revokeObjectURL(url);setSource('');};},[open,video?.id]); // eslint-disable-line react-hooks/exhaustive-deps
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="practice-player-dialog" data-testid="practice-video-dialog"><DialogHeader><DialogTitle data-testid="practice-video-dialog-title">{video?.title}</DialogTitle><DialogDescription data-testid="practice-video-dialog-meta">{video?.therapy} · {video&&dateLabel(`${video.session_date}T12:00:00+05:30`)}</DialogDescription></DialogHeader><div className="practice-player-stage">{loading?<div className="practice-player-state" role="status" data-testid="practice-video-loading">Preparing the secure video…</div>:error?<div className="error-message" role="alert" data-testid="practice-video-error">{error}</div>:source?<video src={source} controls playsInline autoPlay data-testid="practice-video-player">Your browser cannot play this video.</video>:null}</div>{video&&<div className="practice-dialog-details"><div className="practice-meta-row"><span data-testid="practice-dialog-date"><CalendarDays/> {dateLabel(`${video.session_date}T12:00:00+05:30`)}</span><span data-testid="practice-dialog-duration"><Clock/> {durationLabel(video.duration_seconds)}</span><span data-testid="practice-dialog-therapist"><UserRound/> {video.therapist_name}</span></div><p data-testid="practice-dialog-note">{video.note}</p><ol data-testid="practice-dialog-steps">{video.steps.map((step,index)=><li key={`${step}-${index}`}><span>{index+1}</span>{step}</li>)}</ol></div>}</DialogContent></Dialog>;
};