import { useEffect, useRef, useState } from 'react';
import { Camera, CircleStop, RotateCcw, Upload, Video } from 'lucide-react';
import { Button } from '../ui/button';

const MAX_BYTES=120*1024*1024;
const formatTime=value=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;

export const VideoRecorder=({value,onChange,onError})=>{
 const liveRef=useRef(null),recorderRef=useRef(null),streamRef=useRef(null),chunksRef=useRef([]),elapsedRef=useRef(0);
 const [recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[preview,setPreview]=useState('');
 const release=()=>{streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(liveRef.current)liveRef.current.srcObject=null;};
 const setSelected=(file,duration=0)=>{if(preview)URL.revokeObjectURL(preview);const next=URL.createObjectURL(file);setPreview(next);onChange({file,durationSeconds:Math.max(1,Math.round(duration||0))});};
 const clear=()=>{if(preview)URL.revokeObjectURL(preview);setPreview('');setElapsed(0);elapsedRef.current=0;onChange(null);};
 const stop=()=>{if(recorderRef.current?.state==='recording')recorderRef.current.stop();setRecording(false);release();};
 const start=async()=>{try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Camera recording is not supported in this browser. Choose a video file instead.');clear();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280}},audio:true});streamRef.current=stream;if(liveRef.current){liveRef.current.srcObject=stream;await liveRef.current.play();}const type=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(t=>window.MediaRecorder.isTypeSupported(t));const recorder=new window.MediaRecorder(stream,type?{mimeType:type,videoBitsPerSecond:1200000}:undefined);chunksRef.current=[];elapsedRef.current=0;setElapsed(0);recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data);};recorder.onstop=()=>{const mime=recorder.mimeType||'video/webm';const blob=new Blob(chunksRef.current,{type:mime});if(blob.size>MAX_BYTES){onError('Recording is over 120 MB. Please make a shorter guide.');return;}setSelected(new File([blob],`home-practice-${Date.now()}.webm`,{type:mime}),elapsedRef.current);};recorder.start(1000);recorderRef.current=recorder;setRecording(true);}catch(error){release();onError(error.message||'Camera access was not available. Choose a video file instead.');}};
 const choose=e=>{const file=e.target.files?.[0];if(!file)return;if(!['video/mp4','video/webm','video/quicktime'].includes(file.type)){onError('Choose an MP4, WebM or MOV video.');e.target.value='';return;}if(file.size>MAX_BYTES){onError('Video must be under 120 MB.');e.target.value='';return;}const url=URL.createObjectURL(file);const probe=document.createElement('video');probe.preload='metadata';probe.onloadedmetadata=()=>{const duration=Number.isFinite(probe.duration)?probe.duration:0;URL.revokeObjectURL(url);if(duration>600){onError('Keep the home-practice guide to 10 minutes or less.');e.target.value='';return;}setSelected(file,duration);};probe.onerror=()=>{URL.revokeObjectURL(url);setSelected(file,0);};probe.src=url;};
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>{elapsedRef.current+=1;setElapsed(elapsedRef.current);if(elapsedRef.current>=600)stop();},1000);return()=>clearInterval(timer);},[recording]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!value&&preview){URL.revokeObjectURL(preview);setPreview('');setElapsed(0);elapsedRef.current=0;}},[value]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>()=>{release();if(preview)URL.revokeObjectURL(preview);},[preview]); // eslint-disable-line react-hooks/exhaustive-deps
 return <div className="video-recorder" data-testid="practice-video-recorder"><div className={`recorder-stage ${recording?'is-recording':''}`}>{recording?<video ref={liveRef} muted playsInline data-testid="practice-live-camera"/>:preview?<video src={preview} controls playsInline preload="metadata" data-testid="practice-video-preview"/>:<div className="recorder-empty" data-testid="practice-recorder-empty"><Video size={34}/><strong>Record only the home-practice steps</strong><span>Up to 10 minutes · MP4, WebM or MOV · 120 MB maximum</span></div>}{recording&&<span className="recording-timer" role="status" data-testid="practice-recording-timer"><i/>{formatTime(elapsed)} / 10:00</span>}</div><div className="recorder-actions">{recording?<Button type="button" className="button recording-stop" onClick={stop} data-testid="practice-stop-recording"><CircleStop/> Stop recording</Button>:<Button type="button" className="button outlined" onClick={start} data-testid="practice-start-recording"><Camera/> Record now</Button>}<label className="button outlined upload-label" data-testid="practice-video-file-label"><Upload size={16}/> Choose video<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={choose} data-testid="practice-video-file-input"/></label>{value&&<button type="button" className="text-link" onClick={clear} data-testid="practice-clear-video"><RotateCcw size={15}/> Choose another</button>}</div>{value&&<p className="selected-file" data-testid="practice-selected-file">{value.file.name} · {(value.file.size/1024/1024).toFixed(1)} MB</p>}</div>;
};