import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, KeyRound, Mail, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { api, errorText } from '../lib/api';
import { useAuth } from '../lib/context';
import { Brand } from '../components/PublicLayout';

const AccessShell=({children})=><main className="auth-page"><Link to="/login" className="auth-back" data-testid="account-access-back"><ArrowLeft/> Back to sign in</Link><section className="auth-panel compact"><Brand/>{children}</section></main>;

export default function AccountAccess({mode}){
 const [params]=useSearchParams(),navigate=useNavigate(),{acceptInvitation}=useAuth(),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[details,setDetails]=useState(null),[form,setForm]=useState({email:'',display_name:'',password:'',confirm:'',token:params.get('token')||''});
 useEffect(()=>{if(mode==='invite'&&form.token)api.get(`/auth/invitations/${form.token}`).then(({data})=>{setDetails(data);setForm(current=>({...current,email:data.email,display_name:data.display_name||''}));}).catch(error=>toast.error(errorText(error)));},[mode,form.token]); // eslint-disable-line react-hooks/exhaustive-deps
 const submit=async event=>{event.preventDefault();if((mode==='invite'||mode==='reset')&&form.password!==form.confirm){toast.error('Passwords do not match.');return;}setBusy(true);try{if(mode==='forgot'){await api.post('/auth/forgot-password',{email:form.email});setDone(true);}else if(mode==='reset'){await api.post('/auth/reset-password',{token:form.token,password:form.password});setDone(true);}else{const next=await acceptInvitation({token:form.token,display_name:form.display_name,password:form.password});navigate(next.mfa_setup_required?'/security-setup':`/portal/${next.role}/${next.role==='admin'?'overview':'today'}`);}}catch(error){toast.error(errorText(error));}finally{setBusy(false);}};
 if(done)return <AccessShell><CheckCircle2 className="access-success-icon"/><span className="eyebrow">REQUEST COMPLETE</span><h1 data-testid="access-success-title">{mode==='forgot'?'Check your email':'Your password is updated'}</h1><p data-testid="access-success-message">{mode==='forgot'?'If an active account matches, a single-use link will arrive shortly.':'Sign in again on every device using your new password.'}</p><Link to="/login" className="button primary" data-testid="access-return-login">Return to sign in</Link></AccessShell>;
 return <AccessShell><span className="eyebrow">{mode==='invite'?'ACCOUNT INVITATION':mode==='reset'?'PASSWORD RESET':'ACCOUNT RECOVERY'}</span><h1 data-testid="account-access-title">{mode==='invite'?'Set up your secure account':mode==='reset'?'Choose a new password':'Find your account'}</h1>{details&&<div className="invitation-summary" data-testid="invitation-summary"><ShieldCheck/><span><strong>{details.email}</strong>{details.access_profile} access · expires {new Date(details.expires_at).toLocaleString('en-IN')}</span></div>}<form onSubmit={submit} data-testid={`${mode}-form`}>{mode==='forgot'&&<div className="field"><label htmlFor="recovery-email">Email address</label><input id="recovery-email" type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required data-testid="recovery-email"/></div>}{mode==='invite'&&<div className="field"><label htmlFor="invite-name">Your full name</label><input id="invite-name" value={form.display_name} onChange={event=>setForm({...form,display_name:event.target.value})} minLength={2} required data-testid="invite-display-name"/></div>}{(mode==='invite'||mode==='reset')&&<><div className="field"><label htmlFor="new-password">New password</label><input id="new-password" type="password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} minLength={12} maxLength={72} autoComplete="new-password" required data-testid="new-password"/><small>At least 12 characters with uppercase, lowercase and a number.</small></div><div className="field"><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" value={form.confirm} onChange={event=>setForm({...form,confirm:event.target.value})} minLength={12} autoComplete="new-password" required data-testid="confirm-password"/></div></>}<button className="button primary full" disabled={busy} data-testid="account-access-submit">{busy?'Please wait…':mode==='forgot'?'Send recovery link':mode==='reset'?'Update password':'Create account'} {mode==='forgot'?<Mail/>:<KeyRound/>}</button></form></AccessShell>;
}