import { useState,useEffect } from 'react';
import { Mail, MessageSquare, CreditCard, Video, Instagram, Save, ShieldCheck, ImagePlus, Trash2, UploadCloud, Users, BellRing, Send } from 'lucide-react';
import { PortalHeading } from '../components/PortalLayout';
import { useOrganization } from '../lib/context';
import { api,errorText,dateLabel,mediaUrl } from '../lib/api';
import { services } from '../lib/content';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';

export const AdminSettings=()=>{
 const [form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [nbusy,setNbusy]=useState(''),[pw,setPw]=useState('');const [watok,setWatok]=useState(''),[wbusy,setWbusy]=useState('');const {reload}=useOrganization();
 useEffect(()=>{api.get('/admin/settings').then(({data})=>setForm({...data,notify_email:data.notify_email||data.email||'',smtp_username:data.smtp_username||'',notify_enabled:!!data.notify_enabled,wa_enabled:!!data.wa_enabled,wa_recipient:data.wa_recipient||data.phone||'',wa_phone_number_id:data.wa_phone_number_id||'',wa_template_name:data.wa_template_name||'',wa_template_language:data.wa_template_language||'en_US'})).catch(e=>setError(errorText(e)));},[]);
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await api.patch('/admin/settings',{email:form.email,phone:form.phone,secondary_phone:form.secondary_phone,address:form.address,version:form.version});setForm(f=>({...f,...data}));reload();toast.success('Organization details saved in this demo. Verification is still required.');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const saveNotify=async e=>{e.preventDefault();setNbusy('save');setError('');try{const {data}=await api.patch('/admin/notifications',{notify_enabled:!!form.notify_enabled,notify_email:form.notify_email||'',smtp_username:form.smtp_username||'',smtp_app_password:pw});setForm(f=>({...f,...data,notify_email:data.notify_email||'',smtp_username:data.smtp_username||'',notify_enabled:!!data.notify_enabled}));setPw('');reload();toast.success('Email alert settings saved.');}catch(e){setError(errorText(e));toast.error(errorText(e));}finally{setNbusy('');}};
 const testNotify=async()=>{setNbusy('test');try{const {data}=await api.post('/admin/notifications/test');toast.success(data.message||'Test email sent.');}catch(e){toast.error(errorText(e));}finally{setNbusy('');}};
 const saveWhatsapp=async e=>{e.preventDefault();setWbusy('save');setError('');try{const {data}=await api.patch('/admin/whatsapp',{wa_enabled:!!form.wa_enabled,wa_recipient:form.wa_recipient||'',wa_phone_number_id:form.wa_phone_number_id||'',wa_access_token:watok,wa_template_name:form.wa_template_name||'',wa_template_language:form.wa_template_language||'en_US'});setForm(f=>({...f,...data,wa_enabled:!!data.wa_enabled,wa_recipient:data.wa_recipient||'',wa_phone_number_id:data.wa_phone_number_id||'',wa_template_name:data.wa_template_name||'',wa_template_language:data.wa_template_language||'en_US'}));setWatok('');toast.success('WhatsApp alert settings saved.');}catch(e){setError(errorText(e));toast.error(errorText(e));}finally{setWbusy('');}};
 const testWhatsapp=async()=>{setWbusy('test');try{const {data}=await api.post('/admin/whatsapp/test');toast.success(data.message||'Test WhatsApp sent.');}catch(e){toast.error(errorText(e));}finally{setWbusy('');}};
 return <><PortalHeading eyebrow="ONE CENTER. CONSISTENT INFORMATION." title="Organization settings" subtitle="Changes apply to your isolated demonstration, including public contact details."/>{error&&<p role="alert" className="error-message" data-testid="settings-error">{error}</p>}{form?<>
  <form className="settings-form" onSubmit={save}>
   <div className="settings-heading"><h2>Published contact information</h2><span className="status yellow" data-testid="settings-verification">{form.verification_status}</span></div>
   <div className="review-panel"><ShieldCheck size={22}/><p>The existing site also shows contact@moonlight.com. Confirm the correct inbox with the center before approval. Saved changes here do not verify ownership.</p></div>
   {[['email','Contact email','email'],['phone','Primary phone','tel'],['secondary_phone','Secondary phone','tel']].map(([key,label,type])=><div className="field" key={key}><label htmlFor={`settings-${key}`}>{label}</label><input id={`settings-${key}`} data-testid={`settings-${key.replaceAll('_','-')}`} type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required/></div>)}
   <div className="field"><label htmlFor="settings-address">Published center address</label><textarea id="settings-address" data-testid="settings-address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required minLength={20}/></div>
   <div className="settings-readonly"><span>Center time zone</span><strong data-testid="settings-timezone">Asia/Kolkata</strong><span>Proposed programs</span><strong>Unpublished · approval required</strong></div>
   <Button type="submit" disabled={busy} className="button primary" data-testid="save-settings"><Save size={17}/>{busy?'Saving…':'Save center details'}</Button>
  </form>
  <form className="settings-form notify-section" onSubmit={saveNotify}>
   <div className="settings-heading"><h2><BellRing size={18} style={{verticalAlign:'-3px',marginRight:'7px'}}/>New enquiry email alerts</h2><span className={`status ${form.smtp_password_set&&form.notify_enabled?'sage':'yellow'}`} data-testid="notify-status">{form.smtp_password_set?(form.notify_enabled?'On':'Saved · off'):'Not configured'}</span></div>
   <div className="review-panel"><ShieldCheck size={22}/><p>Get an email the moment a family submits an assessment enquiry. Use a Gmail account with a 16-character <strong>App Password</strong> (Google Account → Security → 2-Step Verification → App passwords). Your normal Gmail password will not work.</p></div>
   <label className="checkbox-row" data-testid="notify-enabled"><input type="checkbox" checked={!!form.notify_enabled} onChange={e=>setForm({...form,notify_enabled:e.target.checked})}/> Email me when a new enquiry arrives</label>
   <div className="field"><label htmlFor="notify-email">Send alerts to (center inbox)</label><input id="notify-email" data-testid="notify-email" type="email" value={form.notify_email} onChange={e=>setForm({...form,notify_email:e.target.value})} placeholder="center@example.com" required/></div>
   <div className="field"><label htmlFor="notify-smtp-user">Sender Gmail address</label><input id="notify-smtp-user" data-testid="notify-smtp-user" type="email" value={form.smtp_username} onChange={e=>setForm({...form,smtp_username:e.target.value})} placeholder="you@gmail.com" required/></div>
   <div className="field"><label htmlFor="notify-pw">Gmail App Password</label><input id="notify-pw" data-testid="notify-app-password" type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder={form.smtp_password_set?'•••••••• saved — leave blank to keep':'16-character app password'} autoComplete="off"/></div>
   <div className="notify-actions">
    <Button type="submit" disabled={nbusy==='save'} className="button primary" data-testid="save-notify"><Save size={16}/>{nbusy==='save'?'Saving…':'Save alert settings'}</Button>
    <button type="button" className="button outlined" data-testid="test-notify" disabled={nbusy==='test'||!form.smtp_password_set} onClick={testNotify}><Send size={15}/>{nbusy==='test'?'Sending…':'Send test email'}</button>
   </div>
  </form>
  <form className="settings-form notify-section" onSubmit={saveWhatsapp}>
   <div className="settings-heading"><h2><MessageSquare size={18} style={{verticalAlign:'-3px',marginRight:'7px'}}/>WhatsApp enquiry alerts</h2><span className={`status ${form.wa_token_set&&form.wa_enabled?'sage':'yellow'}`} data-testid="wa-status">{form.wa_token_set?(form.wa_enabled?'On':'Saved · off'):'Not configured'}</span></div>
   <div className="review-panel"><ShieldCheck size={22}/><p>Ping the center on WhatsApp for every new enquiry via the Meta WhatsApp Cloud API (Graph API v26.0). First create an <strong>approved message template</strong> whose body has 3 variables in this order — 1) family name, 2) phone, 3) interest — then paste the details below. The access token is stored securely and never shown again.</p></div>
   <label className="checkbox-row" data-testid="wa-enabled"><input type="checkbox" checked={!!form.wa_enabled} onChange={e=>setForm({...form,wa_enabled:e.target.checked})}/> Send a WhatsApp alert when a new enquiry arrives</label>
   <div className="field"><label htmlFor="wa-recipient">Center WhatsApp number (with country code)</label><input id="wa-recipient" data-testid="wa-recipient" value={form.wa_recipient} onChange={e=>setForm({...form,wa_recipient:e.target.value})} placeholder="+91 7982282025"/></div>
   <div className="field"><label htmlFor="wa-phone-id">Phone Number ID</label><input id="wa-phone-id" data-testid="wa-phone-id" value={form.wa_phone_number_id} onChange={e=>setForm({...form,wa_phone_number_id:e.target.value})} placeholder="e.g. 987654321098765"/></div>
   <div className="field"><label htmlFor="wa-token">Permanent access token</label><input id="wa-token" data-testid="wa-access-token" type="password" value={watok} onChange={e=>setWatok(e.target.value)} placeholder={form.wa_token_set?'•••••••• saved — leave blank to keep':'System-user access token'} autoComplete="off"/></div>
   <div className="field"><label htmlFor="wa-template">Approved template name</label><input id="wa-template" data-testid="wa-template-name" value={form.wa_template_name} onChange={e=>setForm({...form,wa_template_name:e.target.value})} placeholder="e.g. new_enquiry_alert"/></div>
   <div className="field"><label htmlFor="wa-lang">Template language code</label><input id="wa-lang" data-testid="wa-template-language" value={form.wa_template_language} onChange={e=>setForm({...form,wa_template_language:e.target.value})} placeholder="en_US"/></div>
   <div className="notify-actions">
    <Button type="submit" disabled={wbusy==='save'} className="button primary" data-testid="save-whatsapp"><Save size={16}/>{wbusy==='save'?'Saving…':'Save WhatsApp settings'}</Button>
    <button type="button" className="button outlined" data-testid="test-whatsapp" disabled={wbusy==='test'||!form.wa_token_set} onClick={testWhatsapp}><Send size={15}/>{wbusy==='test'?'Sending…':'Send test WhatsApp'}</button>
   </div>
  </form>
 </>:!error&&<p data-testid="settings-loading" role="status">Loading settings…</p>}</>;
};
export const AdminIntegrations=()=> <><PortalHeading eyebrow="CONNECTED ONLY WHEN READY" title="Provider connections" subtitle="No provider is connected. No payments, messages, video meetings or social feeds are being sent or processed."/><div className="integration-grid">{[[CreditCard,'Payments','Razorpay or an approved hosted checkout','Merchant approval, credentials, signatures, reconciliation and failure-path tests.'],[Mail,'Email','Verified transactional email provider','Verified sender, delivery events, consent checks and a test-recipient allowlist.'],[MessageSquare,'WhatsApp','Official WhatsApp Business provider','Approved account and templates, consent categories, opt-outs and delivery events.'],[Video,'Video sessions','Established video provider','Entitlements, waiting room, host controls and purpose-specific consent.'],[Instagram,'Instagram','Official authorized API or curated CMS','Verified center account, token checks and moderation. No scraping.']].map(([Icon,title,provider,description],i)=><article className="integration-card" key={title} data-testid={`integration-${i}`}><div><Icon size={26}/><span className="status yellow">Not Configured</span></div><h2>{title}</h2><strong>{provider}</strong><p>{description}</p></article>)}</div><div className="review-panel"><ShieldCheck size={22}/><p>Credentials alone do not establish that an integration works. Each provider requires approved configuration and acceptance tests before activation.</p></div></>;
export const AdminAudit=()=>{
 const [items,setItems]=useState(null),[error,setError]=useState('');
 useEffect(()=>{api.get('/admin/audit').then(({data})=>setItems(data.items.reverse())).catch(e=>setError(errorText(e)));},[]);
 return <><PortalHeading eyebrow="ACCOUNTABILITY AT EVERY STEP" title="Audit trail" subtitle="Scoped access decisions and updates. Sensitive content is never included in event descriptions."/>{error?<p role="alert" data-testid="audit-error">{error}</p>:!items?<p role="status" data-testid="audit-loading">Loading audit events…</p>:<div className="audit-list">{items.map(item=><div key={item.id} className="audit-row" data-testid={`audit-${item.id}`}><ShieldCheck size={17}/><div><strong>{item.action}</strong><p>{item.resource_id||'Workspace'} · {dateLabel(item.created_at)}</p></div><span className={`status ${item.result==='allowed'?'sage':'peach'}`}>{item.result}</span></div>)}</div>}</>;
};
export const AdminChecklist=()=> <><PortalHeading eyebrow="THE COMPLETE SCOPE, KEPT IN VIEW" title="One foundation. Five thoughtful phases." subtitle="Stage A checkpoint · Later modules remain in the requirements matrix, not silently omitted."/><div className="phase-list">{[['A','Foundation & design checkpoint','Implemented','Public homepage, eight service drafts, enquiry capture, isolated cookie sessions, parent Today, staff agenda, admin overview, and handoff specifications.'],['B','Public content & care coordination','Needs Configuration','Reviewed content/CMS, server-rendered public pages, URL migration, invitations and per-child guardian permissions, conflict-safe scheduling and admission processing.'],['C','Everyday care workflows','Needs Configuration','Signed clinical notes, secure files, classroom workflows, QR/location attendance, verified pickup, immutable package ledger, payments and consent-aware service notices.'],['D','Learning & community','Needs Configuration','Approved academy and cohort enrollment, video integration, entitled live sessions, event approvals, social moderation and international journeys.'],['E','Operations & discoverability','Needs Configuration','Reviewed local pages, reconciled reporting, backups and restore rehearsal, legal and operational readiness, optional controlled AI assistance.']].map(([stage,title,status,description])=><article className="phase-item" key={stage} data-testid={`phase-${stage}`}><span>{stage}</span><div><div><h2>{title}</h2><span className={`status ${stage==='A'?'sage':'yellow'}`}>{status}</span></div><p>{description}</p></div></article>)}</div><div className="review-panel"><ShieldCheck size={22}/><p>All clinical content, real center imagery, team credentials, fees and optional offerings are pending approval. Stage A is not authorized for real child records.</p></div></>;
export const AdminMedia=()=>{
 const [s,setS]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const [tn,setTn]=useState(''),[tr,setTr]=useState(''),[tf,setTf]=useState(null);const {reload}=useOrganization();
 useEffect(()=>{api.get('/admin/settings').then(({data})=>setS(data)).catch(e=>setError(errorText(e)));},[]);
 const send=async(slot,file,extra={},busyKey)=>{setBusy(busyKey||slot);setError('');try{const fd=new FormData();fd.append('slot',slot);if(file)fd.append('file',file);Object.entries(extra).forEach(([k,v])=>fd.append(k,v));const {data}=await api.post('/admin/media',fd);setS(data);reload();toast.success('Saved to this demonstration workspace.');}catch(e){setError(errorText(e));toast.error(errorText(e));}finally{setBusy('');}};
 const remove=async(slot,value)=>{setBusy(slot+value);try{const {data}=await api.post('/admin/media/remove',{slot,value});setS(data);reload();}catch(e){toast.error(errorText(e));}finally{setBusy('');}};
 if(!s)return <><PortalHeading eyebrow="YOUR SITE, YOUR IMAGES" title="Site images"/>{error?<p className="error-message" role="alert" data-testid="media-error">{error}</p>:<p role="status" data-testid="media-loading">Loading images…</p>}</>;
 const heroes=s.hero_images||[],team=s.team||[],ti=s.therapy_images||{};
 return <><PortalHeading eyebrow="YOUR SITE, YOUR IMAGES" title="Site images" subtitle="Upload and manage the pictures shown on your public website. Changes apply to this demonstration workspace."/>{error&&<p className="error-message" role="alert" data-testid="media-error">{error}</p>}
  <section className="portal-section"><div className="portal-section-heading"><h2><ImagePlus size={19}/> Homepage hero slideshow</h2></div><p className="muted small">Rotating images at the top of the homepage. Add a few for a lively, moving hero.</p><div className="media-thumbs">{heroes.map(h=><div className="media-thumb" key={h} data-testid="hero-thumb"><img src={mediaUrl(h)} alt=""/><button onClick={()=>remove('hero',h)} data-testid="hero-remove" aria-label="Remove image"><Trash2 size={15}/></button></div>)}<label className="media-upload" data-testid="hero-upload"><ImagePlus size={22}/><span>{busy==='hero'?'Uploading…':'Add image'}</span><input type="file" accept="image/*" onChange={e=>e.target.files[0]&&send('hero',e.target.files[0])}/></label></div><p className="muted small" style={{marginTop:'10px'}}>No custom images means the default warm slideshow is shown.</p></section>
  <section className="portal-section"><div className="portal-section-heading"><h2><ImagePlus size={19}/> Therapy images</h2></div><p className="muted small">Replace the default photo shown for each therapy on the homepage and Therapies page with your own session photos (shared with consent).</p><div className="therapy-admin-grid">{services.map(svc=>{const ov=ti[svc.slug];const src=ov?mediaUrl(ov):svc.image;const b=`therapy-${svc.slug}`;return <div className="therapy-admin-card" key={svc.slug} data-testid={`therapy-media-${svc.slug}`}><img src={src} alt={svc.title}/><div className="therapy-admin-body"><strong>{svc.title}</strong><span className={`status ${ov?'sage':'yellow'}`}>{ov?'Custom photo':'Default photo'}</span><div className="therapy-admin-actions"><label className="button outlined"><UploadCloud size={14}/> {busy===b?'Uploading…':'Replace'}<input type="file" accept="image/*" onChange={e=>e.target.files[0]&&send('therapy',e.target.files[0],{slug:svc.slug},b)}/></label>{ov&&<button type="button" data-testid={`therapy-reset-${svc.slug}`} disabled={busy==='therapy'+svc.slug} onClick={()=>remove('therapy',svc.slug)}>Reset</button>}</div></div></div>;})}</div></section>
  <section className="portal-section"><div className="portal-section-heading"><h2>Director photo</h2></div><div className="media-single">{s.director_photo?<img src={mediaUrl(s.director_photo)} alt="Director"/>:<span className="media-empty">Using the default photo</span>}<label className="button outlined" data-testid="director-upload"><UploadCloud size={16}/> {busy==='director'?'Uploading…':'Replace photo'}<input type="file" accept="image/*" onChange={e=>e.target.files[0]&&send('director',e.target.files[0])}/></label></div></section>
  <section className="portal-section"><div className="portal-section-heading"><h2>Team / center group photo</h2></div><div className="media-single">{s.team_photo?<img src={mediaUrl(s.team_photo)} alt="Team"/>:<span className="media-empty">No group photo yet</span>}<label className="button outlined" data-testid="teamphoto-upload"><UploadCloud size={16}/> {busy==='team_photo'?'Uploading…':(s.team_photo?'Replace photo':'Upload photo')}<input type="file" accept="image/*" onChange={e=>e.target.files[0]&&send('team_photo',e.target.files[0])}/></label></div></section>
  <section className="portal-section"><div className="portal-section-heading"><h2><Users size={19}/> Team members</h2></div><p className="muted small">Added members replace the placeholder cards on the About page.</p><div className="team-admin-grid">{team.map(m=><div className="team-admin-card" key={m.id} data-testid="team-admin-card">{m.photo?<img src={mediaUrl(m.photo)} alt={m.name}/>:<span className="team-avatar"><Users size={22}/></span>}<div><strong>{m.name}</strong><span>{m.role}</span></div><button onClick={()=>remove('team',m.id)} data-testid="team-remove" aria-label="Remove member"><Trash2 size={15}/></button></div>)}</div>
    <div className="team-add-form"><input type="text" placeholder="Full name" value={tn} onChange={e=>setTn(e.target.value)} data-testid="team-add-name"/><input type="text" placeholder="Role (e.g. Speech Therapist)" value={tr} onChange={e=>setTr(e.target.value)} data-testid="team-add-role"/><label className="button outlined"><ImagePlus size={15}/> {tf?tf.name.slice(0,12):'Photo'}<input type="file" accept="image/*" onChange={e=>setTf(e.target.files[0])}/></label><button className="button primary" data-testid="team-add-submit" disabled={busy==='team'||!tn.trim()||!tr.trim()} onClick={async()=>{await send('team',tf,{name:tn,role:tr});setTn('');setTr('');setTf(null);}}>{busy==='team'?'Adding…':'Add member'}</button></div>
  </section></>;
};
