import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowUpRight, ArrowRight, MapPin, Heart, Check, Leaf } from 'lucide-react';
import { HERO_IMAGES, concerns, services, sports } from '../lib/content';
import { mediaUrl } from '../lib/api';
import { useOrganization, useBooking } from '../lib/context';
import { SectionHeading, ServiceGrid, GettingStarted, FAQSection, FinalCTA, CarePrinciples, SportsShowcase, DirectorSection, Reveal } from '../components/PublicSections';
import GoogleReviews from '../components/GoogleReviews';
import { AreasWeServe } from './Locations';

const HERO_EASE = [0.22, 1, 0.36, 1];
const heroContainer = { hidden:{}, show:{ transition:{ staggerChildren:0.13, delayChildren:0.08 } } };
const heroItem = { hidden:{ opacity:0, y:26 }, show:{ opacity:1, y:0, transition:{ duration:0.65, ease:HERO_EASE } } };
const lineWrap = { hidden:{}, show:{ transition:{ staggerChildren:0.14, delayChildren:0.04 } } };
const lineUp = { hidden:{ y:'115%' }, show:{ y:0, transition:{ duration:0.9, ease:HERO_EASE } } };

export default function Home(){
  const [selected,setSelected] = useState(null);
  const {organization:org} = useOrganization();
  const {openBooking} = useBooking();
  const heroImages = (org?.hero_images?.length ? org.hero_images.map(mediaUrl) : HERO_IMAGES);
  const [slide,setSlide] = useState(0);
  useEffect(()=>{ if(heroImages.length<2) return; const t=setInterval(()=>setSlide(s=>(s+1)%heroImages.length),5000); return ()=>clearInterval(t); },[heroImages.length]);
  return <>
    <section className="hero"><div className="hero-slides">{heroImages.map((src,i)=><img key={src+i} className={`hero-image ${i===slide?'active':''}`} src={src} alt="Children and families at Moonlight Neurocare" fetchPriority={i===0?'high':undefined}/>)}</div><div className="hero-wash"/><div className="hero-orbs" aria-hidden="true"><motion.span className="orb orb-1" animate={{y:[0,-22,0]}} transition={{duration:9,repeat:Infinity,ease:'easeInOut'}}/><motion.span className="orb orb-2" animate={{y:[0,18,0]}} transition={{duration:11,repeat:Infinity,ease:'easeInOut'}}/><motion.span className="orb orb-3" animate={{scale:[1,1.14,1]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}}/></div><div className="container hero-inner"><motion.div className="hero-copy" variants={heroContainer} initial="hidden" animate="show"><motion.span className="hero-eyebrow" variants={heroItem} data-testid="hero-location"><span/> CHILD DEVELOPMENT & FAMILY SUPPORT · GURUGRAM</motion.span><motion.h1 variants={heroItem} data-testid="hero-title"><motion.span className="reveal-line" variants={lineWrap}><motion.span className="reveal-word" variants={lineUp}>Support for your child.</motion.span></motion.span><motion.span className="reveal-line" variants={lineWrap}><motion.span className="reveal-word grad-text" variants={lineUp}>Guidance for your family.</motion.span></motion.span></motion.h1><motion.p variants={heroItem} data-testid="hero-description">A little understanding can open up a world of possibility.<br className="desktop-break"/> Thoughtful support for communication, everyday skills<br className="desktop-break"/> and learning — at your child’s pace.</motion.p><motion.div className="hero-buttons" variants={heroItem}><button onClick={openBooking} className="button primary" data-testid="hero-book-assessment">Book an assessment <ArrowUpRight size={18}/></button><Link to="/therapies" className="button ghost-button" data-testid="hero-explore-therapies">Explore therapies <ArrowRight size={17}/></Link></motion.div><motion.span className="hero-booking-note" variants={heroItem} data-testid="hero-request-disclaimer"><Check size={14}/> Start with a request. We’ll confirm the next steps together.</motion.span></motion.div></div></section>
    <CarePrinciples/>
    <section className="concern-section section-pad"><div className="container"><div className="concern-intro"><div><span className="eyebrow">LET’S START WITH WHAT MATTERS TO YOU</span><h2 className="section-title" data-testid="concern-title">What would you like support with?</h2></div><p>No labels needed. Just a place to start.</p></div><div className="concern-options">{concerns.map(({name,icon:Icon},i)=><button key={name} onClick={()=>setSelected(selected===i?null:i)} aria-pressed={selected===i} className={selected===i?'concern selected':'concern'} data-testid={`concern-${i}`}><Icon size={22} strokeWidth={1.5}/><span>{name}</span><ArrowUpRight size={14}/></button>)}</div>{selected!==null&&(()=>{const c=concerns[selected];const empty=!c.slugs.length&&!(c.sports&&c.sports.length);return <div className="concern-result" role="status" data-testid="concern-result"><div><strong>{empty?'It’s okay not to know where to start.':'A few places to begin exploring'}</strong><p>This is information, not a screening or diagnosis. A qualified professional can discuss your child’s needs.</p></div><div>{c.slugs.map(slug=><Link key={slug} to={`/therapies/${slug}`} data-testid={`concern-result-${slug}`}>{services.find(s=>s.slug===slug).title}<ArrowUpRight size={15}/></Link>)}{(c.sports||[]).map(slug=><Link key={slug} to={`/sports/${slug}`} data-testid={`concern-result-${slug}`}>{sports.find(s=>s.slug===slug).title}<ArrowUpRight size={15}/></Link>)}<Link to="/book-assessment" data-testid="concern-talk-team">Talk to the team <ArrowUpRight size={15}/></Link></div></div>;})()}</div></section>
    <section className="therapies-section section-pad"><div className="container"><SectionHeading id="therapies" eyebrow="DIFFERENT NEEDS. THOUGHTFUL SUPPORT." title="Care that meets your child where they are." description="Explore our therapies. Find out what the next step could look like for your family." link={{to:'/therapies',label:'All therapies'}}/><ServiceGrid/></div></section>
    <SportsShowcase/>
    <GettingStarted/>
    <section className="partnership-section section-pad"><div className="container partnership-grid"><div><span className="eyebrow">TOGETHER, BEYOND THE SESSION</span><h2 className="section-title" data-testid="partnership-title">You know your child.<br/>We value what you know.</h2><p>Your questions, observations and everyday moments matter. Shared goals and thoughtful home activities help keep your family part of the conversation.</p><ul className="check-list"><li><Check size={17}/> Goals shaped around everyday life</li><li><Check size={17}/> Space to share what’s working — and what isn’t</li><li><Check size={17}/> Updates that make sense to your family</li></ul><Link className="text-link" to="/for-parents" data-testid="partnership-link">Our partnership with parents <ArrowUpRight size={18}/></Link></div><div className="portal-preview"><div className="preview-header"><span><Heart size={17}/> A LITTLE WINDOW INTO THEIR DAY</span><span className="status sage">Fictional demo</span></div><h3 data-testid="portal-preview-greeting">Hello, Aarav’s family <span>☀</span></h3><p>Every little moment matters.</p><div className="preview-activity"><span className="preview-leaf"><Leaf size={24}/></span><div><span>THIS WEEK’S HOME ACTIVITY</span><h4>A little choice, a meaningful moment</h4><p>Communication through child-led play</p></div><ArrowUpRight size={20}/></div><div className="preview-bottom"><span><Check size={15}/> At your family’s pace</span><Link to="/login" data-testid="preview-portal-link">Explore parent portal <ArrowRight size={16}/></Link></div></div></div></section>
    <DirectorSection/>
    <AreasWeServe/>
    <GoogleReviews/>
    <section className="visit-band"><div className="container visit-inner"><span className="visit-icon"><MapPin size={28}/></span><div><span className="eyebrow">A PLACE TO BEGIN</span><h2 data-testid="visit-center-title">Find us in Sector 37C, Gurugram.</h2><p>Opposite Alpine Convent School · Center details awaiting verification</p></div><Link className="button outlined" to="/locations/gurugram-sector-37c" data-testid="home-directions">Plan your visit <ArrowUpRight size={17}/></Link></div></section>
    <FAQSection/><FinalCTA/>
  </>;
}