import { Link, useLocation, useParams } from 'react-router-dom';
import { ArrowUpRight, Phone, Mail, MapPin, ShieldCheck } from 'lucide-react';
import { useOrganization } from '../lib/context';
import { GettingStarted, FAQSection, FinalCTA, DirectorSection, TeamSection, CenterGallery } from '../components/PublicSections';

const pages={
 '/about':{eyebrow:'MOONLIGHT NEUROCARE',title:'Every child brings their own light.',intro:'A child-centered starting point for communication, everyday skills and learning support in Gurugram.',sections:[['A place for your family’s questions','The center’s published services include speech, occupational, ABA, sensory integration, yoga, neurodevelopmental, remedial, and music & play therapies. Individual suitability should be discussed with an appropriately qualified professional.'],['A story built on verified facts','We are reviewing the center’s history, professional credentials, accessibility details and approved photographs. We will not present unverified staff identities, credentials or outcome claims.'],['Your priorities matter','Support should recognize your child’s strengths, respect their choices, and make room for the everyday experiences that matter to your family.']]},
 '/our-approach':{eyebrow:'OUR APPROACH',title:'Listen first. Plan together.',intro:'Individual goals, family involvement, and room to reflect.',sections:[['Understand the everyday context','A useful first conversation starts with your family’s priorities and your child’s preferences.'],['Respect all communication','Speech, AAC, gestures, pictures and other communication preferences all deserve space.'],['Review, not promise','Meaningful progress is individual. We do not promise cures, guaranteed speech or a fixed recovery timeline.']]},
 '/for-parents':{eyebrow:'YOUR FAMILY IS PART OF THE TEAM',title:'Support doesn’t stop at the session.',intro:'Shared goals, small everyday moments, and a clear conversation about what comes next.',sections:[['One place for your day','The parent demonstration includes your child’s upcoming sessions, a shared summary, a home activity and classroom news.'],['Share what you notice','You can record feedback on a demonstration home activity and ask for an adaptation. No streaks, scores or comparison with other children.'],['Make changes together','A reschedule or absence request remains pending. Submitting a request does not alter a confirmed appointment.']]},
 '/fees':{eyebrow:'CLEAR INFORMATION BEFORE YOU DECIDE',title:'Let’s talk about the practical details.',intro:'Fees and payment policies must be confirmed by the center before you commit.',sections:[['Ask for a written breakdown','Request the assessment fee, applicable session fees, package conditions and any tax treatment before accepting a plan. No pricing has been approved for this preview.'],['Cancellations and refunds','Ask about notice periods, cancellation charges, package expiry and refund conditions. These rules require center approval and are not inferred here.'],['Payments in this preview','No payment provider is connected. This preview cannot charge a card, collect a payment or issue a verified payment receipt.']]},
 '/center':{eyebrow:'PLAN A COMFORTABLE VISIT',title:'A familiar first step in Gurugram.',intro:'The center’s published address is in Sector 37C, opposite Alpine Convent School.',sections:[['Access needs','Please contact the center about step-free access, lifts, toilets, sensory needs, parking and any other accommodation before visiting. These facilities have not yet been verified.'],['Photos and tours','Only approved, consented photographs of the actual center will appear here. The homepage image is an explicitly labeled staging illustration.']]},
 '/resources':{eyebrow:'KNOWLEDGE WITH CARE',title:'Helpful information. Thoughtfully reviewed.',intro:'Practical next steps for families, without scores or labels.',sections:[['Preparing for your first conversation','Think about what matters to your child, their preferred communication, and the everyday activities you would like to discuss. You do not need to share detailed medical history in a public enquiry.'],['A note on clinical resources','Clinical guides, milestone explanations, downloadable resources and workshop recordings will remain unpublished until qualified review and any required media consent are complete.']]},
 '/international/families-visiting-india':{eyebrow:'FAMILIES VISITING INDIA',title:'Planning from afar. Staying connected.',intro:'Administrative planning for a visit to the Indian center in Sector 37C, Gurugram.',sections:[['Start with an enquiry','Discuss your intended dates, contact time zone, accessibility needs and the information the team needs before assessing suitability. No appointment availability or travel time is promised.'],['Share documents securely','Do not send medical histories through public enquiry forms. Secure document intake is a later-stage feature and is not enabled in this preview.'],['Clinical services across borders','Overseas clinical sessions remain disabled until professional and jurisdiction requirements are confirmed. Parent education and clinical therapy are different services.']]},
 '/international/dubai-to-gurugram':{eyebrow:'DUBAI TO GURUGRAM',title:'Planning Child Therapy in Gurugram from Dubai',intro:'This is a planning guide for visiting India, not a claim of a Dubai branch or overseas clinical service.',sections:[['Before travel','Contact the Gurugram center about suitability, availability and the lead time required before booking travel. There is no verified standard notice period.'],['Time zones','Dubai uses Asia/Dubai (UTC+4); Gurugram uses Asia/Kolkata (UTC+5:30). India is 1 hour 30 minutes ahead. Confirm the zone on every appointment.'],['Documents and continuity','Ask the team how documents can be shared securely and discuss continuity after returning home. Cross-border clinical sessions are not enabled.']]},
};
const policies={
 privacy:['Privacy information','This Stage A preview is for fictional data only. Assessment enquiries record a guardian name, phone number, optional email, broad service interest, country and contact preferences. They are saved to an isolated demonstration workspace, not sent to a live care team.','Contact consent is separate from marketing, treatment, recording and public image consent. No marketing checkbox is preselected. Please do not enter health histories or upload child records.','A production privacy notice, vendor/data-flow inventory, retention schedule and legal review are required before real data is accepted. For questions or correction requests, contact the center using its published contact details, pending verification.'],
 terms:['Website terms','This is an unapproved demonstration, not a live clinical service. Information does not diagnose a child or determine an individual treatment plan.','An assessment form submits a request only. Availability, suitability, fees and policies need human confirmation.','Final website terms and applicable legal requirements await center and legal review.'],
 accessibility:['Accessibility','This preview is designed for keyboard navigation, visible focus, readable labels and reduced-motion preferences. Please tell the center if you need information in another format.','English is the initial language. Reviewed translations, captioned center media, formal assistive-technology checks and an accessibility statement are pending.','Contact the center to discuss physical access needs before visiting. Do not assume step-free access or particular facilities.'],
 'child-safeguarding':['Child safeguarding','Respect for children’s dignity, autonomy, communication preferences and privacy is part of the product requirements. Publicity consent must never be a condition of receiving support.','No real child media or private therapy recordings are published in this preview. The homepage image is an AI-generated staging illustration.','The center must approve its safeguarding lead, reporting procedure, pickup verification and emergency escalation policy before live operations. If a child is in immediate danger, contact local emergency services.'],
 complaints:['Complaints & contact','If you have a concern about information in this preview, please contact the center. Its published details are shown on the contact page and still require confirmation.','A named complaints contact, response time and escalation process must be approved before launch. This portal is not an emergency service.'],
 cancellation:['Appointment cancellations & refunds','Cancellation windows, fee consequences, package expiry and refund rules have not yet been approved. A parent change request does not confirm cancellation or rescheduling.','Please obtain the current written terms from the center before agreeing to or paying for services. No payments are accepted here.'],
 'online-classes':['Online class terms','Online classes and academy programs are proposed offerings. They are not available for enrollment in this preview.','Admission, provider access, time zones, recording consent, refunds and jurisdiction restrictions need approval before activation. Recording is off by default.'],
 consent:['Understanding consent','Treatment, school/professional sharing, transactional messaging, marketing, session recording and public image use require separate purpose-specific choices.','Consent must record scope, version, signer, timestamp and withdrawal. Declining publicity must not affect access to therapy. These complete workflows are scheduled for later phases.'],
};

export default function Information(){
 const {pathname}=useLocation(),{policy}=useParams(),{organization:org}=useOrganization();
 if(pathname==='/faqs')return <FAQSection/>;
 if(pathname==='/what-to-expect')return <><div className="container page-heading"><span className="eyebrow">YOUR FIRST VISIT</span><h1 data-testid="what-expect-title">A little clarity.<br/>A more comfortable beginning.</h1><p>Ask about access needs, what to bring, fees and your child’s preferred way of communicating before your visit.</p></div><GettingStarted/><FinalCTA/></>;
 if(pathname==='/contact'||pathname.startsWith('/locations/'))return <section className="container section-pad contact-page"><span className="eyebrow">LET’S FIND YOUR NEXT STEP</span><h1 data-testid="contact-title">A conversation starts here.</h1><p>Visit the center in Gurugram, or get in touch with your questions.</p><div className="contact-grid"><div><span className="status yellow" data-testid="contact-verification">Published details · pending center verification</span><div className="contact-detail"><MapPin/><div><h2>Moonlight Neurocare</h2><p data-testid="contact-address">{org?.address||'Contact information is loading.'}</p></div></div><div className="contact-detail"><Phone/><div><h2>Call the center</h2>{[org?.phone,org?.secondary_phone].filter(Boolean).map((phone,i)=><a key={phone} href={`tel:${phone.replaceAll(' ','')}`} data-testid={`contact-phone-${i}`}>{phone}</a>)}</div></div><div className="contact-detail"><Mail/><div><h2>Email</h2><a href={org?`mailto:${org.email}`:undefined} data-testid="contact-email">{org?.email||'Loading…'}</a></div></div><Link to="/book-assessment" className="button primary" data-testid="contact-book">Request an assessment<ArrowUpRight size={17}/></Link></div><div className="directions-panel"><MapPin size={42} strokeWidth={1.3}/><span className="eyebrow">SECTOR 37C · GURUGRAM</span><h2>Opposite Alpine Convent School</h2><p>Near Param Ultrasound. Ask the team about parking, building access and arrival arrangements before your visit.</p><a data-testid="open-directions" target="_blank" rel="noreferrer" className="button outlined" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(org?.address||'Moonlight Neurocare Sector 37C Gurugram')}`}>Open directions <ArrowUpRight size={17}/></a><span className="small muted">Opens Google Maps on request. Coordinates are not verified.</span></div></div></section>;
 if(policy){const data=policies[policy];if(!data)return <NotFound/>;return <section className="container section-pad policy-page"><span className="eyebrow">TRUST & TRANSPARENCY</span><h1 data-testid="policy-title">{data[0]}</h1><span className="editorial-label">Stage A explanation · final policy pending approval</span>{data.slice(1).map((paragraph,i)=><p key={i} data-testid={`policy-paragraph-${i}`}>{paragraph}</p>)}<Link to="/contact" className="text-link" data-testid="policy-contact">Contact the center<ArrowUpRight size={17}/></Link></section>;}
 const data=pages[pathname];if(!data)return <NotFound/>;
 return <><section className="container page-heading"><span className="eyebrow">{data.eyebrow}</span><h1 data-testid="information-title">{data.title}</h1><p data-testid="information-introduction">{data.intro}</p></section><section className="container information-sections">{data.sections.map(([title,copy],i)=><article key={title} data-testid={`information-section-${i}`}><span className="section-number">0{i+1}</span><div><h2>{title}</h2><p>{copy}</p></div></article>)}{pathname==='/for-parents'&&<Link className="button primary" to="/login?demo=parent" data-testid="parents-demo-link">Explore the parent demonstration<ArrowUpRight size={17}/></Link>}{pathname==='/international/families-visiting-india'&&<Link className="text-link" to="/international/dubai-to-gurugram" data-testid="dubai-guide-link">Planning from Dubai<ArrowUpRight size={17}/></Link>}{pathname==='/resources'&&<div className="resource-links"><Link to="/what-to-expect" data-testid="resource-first-visit">Preparing for a first visit <ArrowUpRight size={17}/></Link><Link to="/policies/consent" data-testid="resource-consent">Understanding consent <ArrowUpRight size={17}/></Link><Link to="/international/families-visiting-india" data-testid="resource-international">Planning a visit from abroad <ArrowUpRight size={17}/></Link></div>}</section>{pathname==='/about'&&<><CenterGallery/><DirectorSection/><TeamSection/></>}<FinalCTA/></>;
}
export const NotFound=()=> <section className="container section-pad not-found"><ShieldCheck size={36}/><span className="eyebrow">THIS PAGE ISN’T HERE</span><h1 data-testid="not-found-title">Let’s find a familiar path.</h1><p>The page may not be published yet, or the address may be incorrect.</p><Link to="/" className="button primary" data-testid="not-found-home">Back to home<ArrowUpRight size={17}/></Link></section>;