import { useState } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { Heart, CalendarDays, LayoutDashboard, ArrowRight, LockKeyhole, ArrowLeft } from 'lucide-react';
import { Brand } from '../components/PublicLayout';
import { Button } from '../components/ui/button';
import { api, errorText } from '../lib/api';
import { useAuth, useOrganization } from '../lib/context';

export default function Login(){
 const [params]=useSearchParams(), navigate=useNavigate(), {accept}=useAuth(), {reload}=useOrganization();
 const [role,setRole]=useState(['parent','staff','admin'].includes(params.get('demo'))?params.get('demo'):'parent');
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const signIn=async (demo=false)=>{setBusy(demo?'demo':'login');setError('');try{const {data}=await api.post(demo?'/auth/demo':'/auth/login',demo?{role}:{email,password});accept(data);reload();navigate(`/portal/${data.role}/${data.role==='admin'?'overview':'today'}`);}catch(e){setError(errorText(e));}finally{setBusy('');}};
 return <div className="login-page"><div className="login-story"><Brand/><div><span className="eyebrow">YOUR FAMILY. YOUR CARE TEAM. CONNECTED.</span><h1 data-testid="login-title">A little closer.<br/>Every step of the way.</h1><p>Your space for the everyday moments,<br/>shared plans, and next steps.</p><div className="login-quote"><Heart size={25} strokeWidth={1.5}/><span>Different journeys.<br/>One circle of support.</span></div></div><Link to="/" data-testid="login-back-home"><ArrowLeft size={16}/> Back to Moonlight Neurocare</Link></div><main className="login-main"><div className="login-form-wrap"><span className="eyebrow">WELCOME TO YOUR PORTAL</span><h2>Good to have you here.</h2><p>Sign in with your invited account.</p><form onSubmit={e=>{e.preventDefault();signIn();}} data-testid="login-form"><div className="field"><label htmlFor="login-email">Email address</label><input data-testid="login-email" id="login-email" type="email" autoComplete="username" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label htmlFor="login-password">Password</label><input data-testid="login-password" id="login-password" type="password" autoComplete="current-password" placeholder="Your password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><Button data-testid="login-submit" disabled={!!busy} className="button primary full-width">{busy==='login'?'Signing in…':'Sign in securely'}<LockKeyhole size={16}/></Button><Link className="account-help" to="/contact" data-testid="login-help">Need an invitation or help with access?</Link></form><div className="demo-divider"><span>OR EXPLORE A DEMONSTRATION</span></div><div className="demo-roles" role="group" aria-label="Choose a demonstration workspace">{[['parent','Parent',Heart],['staff','Care team',CalendarDays],['admin','Admin',LayoutDashboard]].map(([value,label,Icon])=><button key={value} type="button" className={role===value?'demo-role active':'demo-role'} aria-pressed={role===value} onClick={()=>setRole(value)} data-testid={`demo-role-${value}`}><Icon size={20}/>{label}</button>)}</div><Button type="button" className="button outlined full-width" disabled={!!busy} onClick={()=>signIn(true)} data-testid="enter-demo">{busy==='demo'?'Preparing your private demo…':`Explore ${role==='staff'?'care team':role} demo`}<ArrowRight size={17}/></Button><p className="demo-disclosure" data-testid="login-demo-disclosure">Fictional families. An isolated workspace for your browser. No real care records, payments or messages.</p>{error&&<div className="error-message" role="alert" data-testid="login-error">{error}</div>}<div className="login-security"><ShieldSymbol/> Private by design. Human at heart.</div></div></main></div>;
}
const ShieldSymbol=()=> <LockKeyhole size={14}/>;