import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowUpRight, CalendarDays, Sprout, MessageSquare, Check, Heart, ChevronDown, CreditCard, Video, ShieldCheck, Clock } from 'lucide-react';
import { useWorkspace, PortalHeading, EmptyState } from '../components/PortalLayout';
import { SessionList } from '../components/SessionList';
import { api, errorText, dateLabel } from '../lib/api';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { ParentPracticePage } from '../components/practice/ParentPractice';

export const ActivityCard=({activity,full=false})=>{
 const {refresh}=useWorkspace();const [feedback,setFeedback]=useState(activity.feedback||''),[busy,setBusy]=useState(false);
 const update=async status=>{setBusy(true);try{await api.patch(`/activities/${activity.id}`,{status,feedback,version:activity.version});toast.success(status==='Need an adaptation'?'Your request for an adaptation has been saved.':'Thank you for sharing your feedback.');refresh();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 return <article className="home-activity-card" data-testid={`activity-${activity.id}`}><div className="activity-top"><span className="service-icon sage"><Sprout size={25}/></span><span className={`status ${activity.status==='Tried it'?'sage':'yellow'}`} data-testid={`activity-status-${activity.id}`}>{activity.status}</span></div><span className="eyebrow">{activity.category}</span><h3>{activity.title}</h3><p>{activity.instructions}</p><span className="activity-footnote">{activity.frequency}</span>{full&&<div className="field"><label htmlFor={`feedback-${activity.id}`}>What did you notice?</label><textarea id={`feedback-${activity.id}`} data-testid={`activity-feedback-${activity.id}`} maxLength={500} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Share a moment, question or difficulty…"/></div>}<div className="activity-actions"><Button className="button primary" data-testid={`activity-tried-${activity.id}`} disabled={busy} onClick={()=>update('Tried it')}><Check size={16}/> We tried it</Button>{full?<button disabled={busy} onClick={()=>update('Need an adaptation')} className="text-link" data-testid={`activity-adapt-${activity.id}`}>Ask for an adaptation</button>:<Link to="/portal/parent/activities" className="text-link" data-testid={`activity-detail-${activity.id}`}>View activity <ArrowUpRight size={15}/></Link>}</div></article>;
};

export default function Parent(){
 const {view='today'}=useParams(),{data}=useWorkspace();const [filter,setFilter]=useState('All sessions');
 const child=data.children[0],next=data.appointments[0];
 if(view==='more')return <MorePage/>;
 if(view==='schedule')return <><PortalHeading eyebrow="A LITTLE CLARITY FOR THE DAYS AHEAD" title="Your family’s schedule" subtitle="Center time · Asia/Kolkata (IST). Changes need the team’s confirmation."/><div className="filter-bar">{['All sessions','Today','Upcoming'].map(f=><button key={f} data-testid={`schedule-filter-${f.toLowerCase().replaceAll(' ','-')}`} aria-pressed={filter===f} className={filter===f?'filter active':'filter'} onClick={()=>setFilter(f)}>{f}</button>)}</div><SessionList sessions={data.appointments.filter(a=>filter==='All sessions'||(filter==='Today'?dateLabel(a.starts_at)===dateLabel(new Date()):new Date(a.starts_at)>new Date()))}/>{data.requests.length>0&&<section className="portal-section"><h2>Requests with the team</h2>{data.requests.map(r=><div className="request-row" key={r.id} data-testid={`pending-request-${r.id}`}><CalendarDays size={20}/><div><strong>{r.kind} · {r.service}</strong><p>{r.preferred_date||'Absence request'} · {r.reason}</p></div><span className="status yellow">{r.status}</span></div>)}</section>}</>;
 if(view==='child')return <><PortalHeading eyebrow="EVERY CHILD, THEIR OWN JOURNEY" title={child?`A little more about ${child.name}`:'My child'} subtitle="Fictional demonstration · Shared information only"/>{!child?<EmptyState title="No child access" description="Your guardian relationship may need review. Contact the center."/>:<><div className="child-profile-header"><span className="child-avatar">{child.initials}</span><div><h2 data-testid="child-name">{child.name}</h2><p>{child.age_label} · Demonstration profile</p></div><span className="status sage">Shared with family</span></div><div className="parent-columns"><section className="portal-section"><h2>Communication preferences</h2><p data-testid="child-communication">{child.communication}</p><h2>Our shared goals</h2><p className="muted small">Examples only — not a personalized treatment plan.</p>{child.goals.map((goal,i)=><div className="goal-row" key={goal} data-testid={`child-goal-${i}`}><span>{i+1}</span><strong>{goal}</strong><Sprout size={19}/></div>)}</section><section className="shared-summary"><span className="eyebrow">A SHARED OBSERVATION</span><h2>Room for the small moments.</h2><p data-testid="child-shared-summary">{child.shared_summary}</p><span className="small muted">Fictional professional observation · No internal clinical notes are shared here.</span></section></div></>}</>;
 if(view==='activities')return <><PortalHeading eyebrow="LITTLE MOMENTS, EVERYDAY CONNECTIONS" title="Home, at your own pace." subtitle="Share what feels useful, and ask for a change when something doesn’t fit."/>{data.activities.length?<div className="activity-page-grid">{data.activities.map(a=><ActivityCard key={a.id} activity={a} full/>)}</div>:<EmptyState icon={Sprout} title="Room for what comes next" description="Assigned home activities will appear here."/>}</>;
 if(view==='practice')return <ParentPracticePage/>;
 if(view==='updates')return <><PortalHeading eyebrow="A WINDOW INTO THEIR DAY" title="Classroom updates" subtitle="Only the updates your family is authorized to see."/>{data.announcements.map(a=><article className="announcement-card" key={a.id} data-testid={`announcement-${a.id}`}><span className="status lavender">{a.category}</span><h2>{a.title}</h2><p>{a.body}</p><span className="small muted">{dateLabel(a.created_at)} · Fictional classroom update</span></article>)}</>;
 return <><PortalHeading title={child?`Hello, ${child.name}’s family.`:'Hello, welcome back.'} subtitle="A new day. A few small steps. We’re here with you." action={child&&<div className="child-switcher" data-testid="child-switcher"><span className="mini-avatar">{child.initials}</span><div><strong>{child.name}</strong><span>{child.age_label} · Demo</span></div><Heart size={18}/></div>}/><div className="parent-quick-stats four"><Link to="/portal/parent/schedule" data-testid="parent-session-stat"><CalendarDays size={22}/><div><strong>{data.appointments.length}</strong><span>Confirmed sessions</span></div><ArrowUpRight size={16}/></Link><Link to="/portal/parent/practice" data-testid="parent-practice-stat"><Video size={22}/><div><strong>{data.practice_unread}</strong><span>New practice videos</span></div><ArrowUpRight size={16}/></Link><Link to="/portal/parent/activities" data-testid="parent-activity-stat"><Sprout size={22}/><div><strong>{data.activities.filter(a=>a.status!=='Tried it').length}</strong><span>Home activities to explore</span></div><ArrowUpRight size={16}/></Link><Link to="/portal/parent/updates" data-testid="parent-update-stat"><MessageSquare size={22}/><div><strong>{data.announcements.length}</strong><span>Classroom updates</span></div><ArrowUpRight size={16}/></Link></div><div className="parent-columns"><div><section className="portal-section"><div className="portal-section-heading"><h2><CalendarDays size={19}/> Your next session</h2><Link to="/portal/parent/schedule" data-testid="parent-view-schedule">View schedule<ArrowUpRight size={16}/></Link></div><SessionList sessions={next?[next]:[]} compact/></section><section className="portal-section"><div className="portal-section-heading"><h2><MessageSquare size={19}/> From the classroom</h2><Link to="/portal/parent/updates" data-testid="parent-all-updates">All updates<ArrowUpRight size={16}/></Link></div>{data.announcements.map(a=><article className="classroom-note" key={a.id} data-testid={`today-announcement-${a.id}`}><span className="status lavender">This week’s learning</span><h3>{a.title}</h3><p>{a.body}</p><span className="small muted">Fictional class · {dateLabel(a.created_at)}</span></article>)}</section></div><section className="portal-section"><div className="portal-section-heading"><h2><Sprout size={19}/> A little moment at home</h2></div>{data.activities.map(a=><ActivityCard key={a.id} activity={a}/>)}</section></div><div className="gentle-note"><Heart size={22} strokeWidth={1.5}/><p>There’s no single pace for progress. The moments that matter are different for every child.</p><Link to="/portal/parent/child" data-testid="parent-shared-goals">Your shared goals <ArrowUpRight size={16}/></Link></div></>;
}

export const MorePage=()=>{const {role}=useWorkspace();return <><PortalHeading eyebrow="YOUR CIRCLE OF SUPPORT" title="A little more, all in one place." subtitle="Additional services will open only after configuration and approval."/><div className="more-grid">{[[MessageSquare,'Secure messages','Not configured','No messaging provider is connected. Contact the center for support; messaging is not an emergency service.'],[CreditCard,'Payments & receipts','Not configured','Payments and real invoices are not enabled. Records will never be withheld because of overdue payment.'],[Video,'Live sessions','Not configured','Video access, consent and host controls require an approved provider. Recording is off.'],[ShieldCheck,'Consent & pickup','Stage C','Purpose-specific consents and verified pickup permissions are planned before live care.']].map(([Icon,title,status,description],i)=><article className="more-item" key={title} data-testid={`more-feature-${i}`}><Icon size={25}/><span className="status yellow">{status}</span><h2>{title}</h2><p>{description}</p></article>)}</div>{role==='parent'&&<div className="resource-links"><Link to="/portal/parent/activities" data-testid="more-home-activities">Home activities<ArrowUpRight size={17}/></Link><Link to="/portal/parent/updates" data-testid="more-classroom-updates">Classroom updates<ArrowUpRight size={17}/></Link></div>}<Link to="/contact" className="button primary" data-testid="more-contact">Contact the center <ArrowUpRight size={17}/></Link></>;};