import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CalendarDays, Users, ClipboardCheck, ArrowUpRight, BookOpen, ShieldCheck } from 'lucide-react';
import { useWorkspace, PortalHeading, EmptyState } from '../components/PortalLayout';
import { SessionList } from '../components/SessionList';
import { MorePage } from './Parent';
import { dateLabel } from '../lib/api';

export default function Staff(){
 const {view='today'}=useParams(),{data}=useWorkspace(),[selected,setSelected]=useState(null),[filter,setFilter]=useState('Today');
 if(view==='more')return <MorePage/>;
 if(view==='classes')return <><PortalHeading eyebrow="SHARED LEARNING, INDIVIDUAL NEEDS" title="Your classes" subtitle="Cohort enrollment and class plans are scheduled for Stage C."/><EmptyState icon={BookOpen} id="staff-classes-empty" title="No approved cohorts yet" description="Assigned children are available in your caseload. Proposed classes remain unpublished until approved." action={<Link to="/portal/staff/children" className="button outlined" data-testid="classes-view-children">View assigned children<ArrowUpRight size={16}/></Link>}/></>;
 if(view==='children')return <><PortalHeading eyebrow="YOUR ASSIGNED CASELOAD" title="Every child. An individual story." subtitle="Fictional profiles · Only children assigned to your demo account are shown."/><div className="children-grid">{data.children.map(c=><button className={`child-record ${selected===c.id?'selected':''}`} key={c.id} data-testid={`staff-child-${c.id}`} onClick={()=>setSelected(selected===c.id?null:c.id)} aria-expanded={selected===c.id}><span className="child-avatar">{c.initials}</span><div><h2>{c.name}</h2><p>{c.age_label}</p><span className="status sage">Assigned to you</span></div><ArrowUpRight size={18}/></button>)}</div>{selected&&(()=>{const c=data.children.find(c=>c.id===selected);return <section className="selected-child" data-testid="staff-selected-child"><h2>{c.name} · Shared context</h2><p>{c.communication}</p><h3>Participation goals</h3><ul className="check-list">{c.goals.map(g=><li key={g}><ClipboardCheck size={17}/>{g}</li>)}</ul><div className="review-panel"><ShieldCheck size={20}/><p>Internal clinical notes, signing and amendment workflows are not enabled in Stage A. These are synthetic shared observations only.</p></div></section>;})()}</>;
 const today=data.appointments.filter(a=>dateLabel(a.starts_at)===dateLabel(new Date()));
 return <><PortalHeading title="A thoughtful start to your day." subtitle="Your agenda, your children, and a little room to plan." action={<span className="status sage">Care team · Demo</span>}/><div className="stat-grid three"><div className="stat-card" data-testid="staff-stat-sessions"><CalendarDays/><span>Today’s sessions</span><strong>{today.length}</strong><small>Scheduled in the demo</small></div><div className="stat-card" data-testid="staff-stat-children"><Users/><span>Assigned children</span><strong>{data.children.length}</strong><small>Your permitted caseload</small></div><div className="stat-card" data-testid="staff-stat-attendance"><ClipboardCheck/><span>Attendance to record</span><strong>{today.filter(a=>a.attendance==='Not recorded').length}</strong><small>Session records, not premises visits</small></div></div><section className="portal-section"><div className="portal-section-heading"><h2><CalendarDays size={20}/> Your daily agenda</h2><div className="filter-bar inline">{['Today','All sessions'].map(f=><button className={filter===f?'filter active':'filter'} aria-pressed={filter===f} data-testid={`staff-filter-${f.replaceAll(' ','-').toLowerCase()}`} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><SessionList sessions={filter==='Today'?today:data.appointments}/></section><div className="staff-bottom"><div><span className="eyebrow">BEFORE THE SESSION</span><h2>Make room for what matters.</h2><p>Review communication preferences and shared goals for the children on your agenda.</p><Link to="/portal/staff/children" className="text-link" data-testid="staff-review-caseload">View your caseload <ArrowUpRight size={17}/></Link></div><div className="documentation-note"><ShieldCheck size={25}/><div><strong>Attendance is one part of the story.</strong><p>Recording presence does not complete a clinical note, confirm a premises check-in, or consume a therapy credit.</p></div></div></div></>;
}