import { MessageCircle, Hand, Sprout, Shapes, PersonStanding, Activity, BookOpen, Music, Footprints, Mountain, Sparkles, Dribbble, Waves } from 'lucide-react';

export const HERO = 'https://static.prod-images.emergentagent.com/jobs/04de8d09-65b6-48d8-b003-b4ea64a19440/images/7830d4cb245eee533294d03f50dca694afa50d25c8c8f3070a7d0f82416adeea.jpeg';
export const LOGO = '/moonlight-logo.svg';
export const DIRECTOR_PHOTO = 'https://customer-assets-gfyr7b9c.emergentagent.net/job_moonlight-prod/artifacts/5phds5ca_image.png';
// Director qualifications — edit these with the verified credentials the center provides.
export const DIRECTOR_QUALS = ['Bachelor of Physiotherapy (BPT)', 'Pediatric rehabilitation focus', 'Credentials pending center verification'];
// Default therapist profiles shown on About until the admin adds real ones from Site images.
export const TEAM_DEFAULTS = [
  { id: 'default-slt', name: 'Speech & Language Therapist', role: 'Communication & early language', bio: 'Supports understanding, expression and everyday communication through playful, child-led sessions — speech, gestures, pictures or AAC.', focus: 'Communication · AAC · feeding' },
  { id: 'default-ot', name: 'Occupational Therapist', role: 'Sensory & everyday skills', bio: 'Helps children build sensory regulation, fine-motor skills and confident participation in daily routines at home and school.', focus: 'Sensory integration · daily-living skills' },
];
export const HERO_IMAGES = [
  HERO,
  'https://static.prod-images.emergentagent.com/jobs/a74c7c56-c89d-4576-8f4a-fc8ed4d3d201/images/06ca992e5d2b0edd33952158f1f99091be529ab3f239dc656e4061e292cff19f.jpeg',
  'https://static.prod-images.emergentagent.com/jobs/a74c7c56-c89d-4576-8f4a-fc8ed4d3d201/images/68a24b83016e136be15c580fce815d6868ba8626514658cafa44d2151af86feb.jpeg',
];
export const services = [
  {slug:'speech-therapy', title:'Speech Therapy', icon:MessageCircle, color:'sage', short:'More ways to communicate. More moments of connection.', intro:'Support for communication, understanding and expressing everyday needs, in the ways that work for your child.', goals:['Communicating choices and needs','Taking part in conversations or shared play','Exploring speech, gestures, pictures or AAC'], audience:'Families seeking support with understanding language, expressing ideas or everyday communication.'},
  {slug:'occupational-therapy', title:'Occupational Therapy', icon:Hand, color:'peach', short:'Building confidence in the little things that make up a day.', intro:'Exploring the everyday activities that matter to your child, from getting dressed to participating in play and learning.', goals:['Taking part in everyday routines','Exploring play and fine-motor activities','Adapting tasks and environments'], audience:'Families looking for support with daily living activities, play or participation at home and school.'},
  {slug:'aba-therapy', title:'ABA Therapy', icon:Sprout, color:'lavender', short:'Individual goals, meaningful skills, and a child-first approach.', intro:'An individualized conversation about learning and participation support, with your child’s comfort, preferences and autonomy at the center.', goals:['Communicating needs and preferences','Learning useful everyday skills','Making participation more accessible'], audience:'Families considering structured learning support. Suitability and methods need individual professional assessment.'},
  {slug:'sensory-integration-therapy', title:'Sensory Integration Therapy', icon:Shapes, color:'yellow', short:'Understanding sensory needs. Making everyday spaces work.', intro:'Understanding how your child experiences the world and exploring supports for comfortable participation in everyday life.', goals:['Identifying comfortable environments','Exploring individualized sensory supports','Participating in chosen activities'], audience:'Families seeking help with sensory preferences or experiences that affect everyday participation.'},
  {slug:'yoga-therapy', title:'Yoga Therapy', icon:PersonStanding, color:'lavender', short:'Gentle movement, body awareness, and room to pause.', intro:'An enquiry into gentle, adapted movement and body-awareness activities. Individual suitability must be discussed with a qualified professional.', goals:['Exploring comfortable movement','Noticing body preferences','Taking part in an enjoyable routine'], audience:'Families exploring adapted movement. Clinical suitability and any precautions need professional review.'},
  {slug:'neurodevelopmental-therapy', title:'Neurodevelopmental Therapy', icon:Activity, color:'sage', short:'Supporting movement and participation at your child’s pace.', intro:'Individual assessment of movement and participation needs, followed by a discussion of possible supports with your family.', goals:['Taking part in meaningful movement','Adapting everyday activities','Supporting comfortable participation'], audience:'Families asking about movement and coordination support. This information is not a diagnosis or recommendation.'},
  {slug:'remedial-therapy', title:'Remedial Therapy', icon:BookOpen, color:'yellow', short:'Different ways to learn. Space to find their own.', intro:'Exploring learning approaches that respond to your child’s strengths, preferences and educational needs.', goals:['Accessing reading or writing activities','Finding useful learning strategies','Building confidence in chosen tasks'], audience:'Families seeking individualized educational support with learning and school participation.'},
  {slug:'music-play-therapy', title:'Music & Play Therapy', icon:Music, color:'peach', short:'Connection and expression through the joy of play.', intro:'Exploring opportunities for connection, expression and participation through child-led play and music.', goals:['Sharing enjoyable play','Exploring creative expression','Communicating preferences'], audience:'Families exploring play-based support. The team will discuss available formats and individual suitability.'},
];
const SPORTS_MEDIA = 'https://static.prod-images.emergentagent.com/jobs/443f7053-1e78-461f-bd20-426ae89c4bb0/images/';
export const SPORTS_HERO = SPORTS_MEDIA + '316dfd0e1b44096e7e5fcffe33d83d0808e032f1f8675bb50b21d911bea70426.jpeg';
export const CENTER_IMAGES = {
  exterior: SPORTS_MEDIA + 'fca2be2e869abbe6cdd3cb82c8652db350736cf9fb233c7d3cc32f61f87341a8.jpeg',
  gym: SPORTS_MEDIA + '372330d081c7493d39c777d154f38b1f09ba19e2135515596543875c6ece3f34.jpeg',
  swings: SPORTS_MEDIA + '55c05fd229e1566bfcd54e1ce8aceee79b4ef0a90e544b1130fba68d3c4233be.jpeg',
  room: SPORTS_MEDIA + 'ffd9624cadd468b48d61cdfa38fadd97a33b43385bccf22ff5327afdc27e980d.jpeg',
};
export const sports = [
  {slug:'roller-skating', title:'Roller Skating', icon:Footprints, color:'sage', image:SPORTS_MEDIA+'88c4f422315c917cb8dff2589d8c0ea061ec3c316e48eaf6dfbfe320454591af.jpeg', short:'Finding balance and confidence, one gentle glide at a time.', intro:'A supported, sensory-friendly introduction to roller skating — at your child’s pace, with plenty of room to pause, watch and try again.', focus:'Balance · coordination · confidence', ages:'Suitable for ages 4–12 · small groups', schedule:[['Tuesday & Thursday','4:00 – 4:45 pm'],['Saturday','10:00 – 10:45 am']], goals:['Exploring balance and weight-shift','Building lower-body coordination','Feeling proud of small wins'], audience:'Children exploring movement and balance in a calm, unhurried indoor space.'},
  {slug:'soft-climbing', title:'Soft Climbing', icon:Mountain, color:'peach', image:SPORTS_MEDIA+'7c77debf34ca65901b430c075854b3631129590f32519761e53f7dd9c3d8f19f.jpeg', short:'Reaching a little higher, with soft mats and steady support.', intro:'A low, safe climbing wall with thick crash mats and warm encouragement — a chance to problem-solve, plan movements and build strength.', focus:'Strength · planning · courage', ages:'Suitable for ages 5–12 · small groups', schedule:[['Wednesday','4:30 – 5:15 pm'],['Saturday','11:00 – 11:45 am']], goals:['Building grip and core strength','Planning a route step by step','Growing comfort with new heights'], audience:'Children who enjoy a physical challenge and want to build strength and motor planning.'},
  {slug:'trampoline-bounce', title:'Trampoline & Bounce', icon:Sparkles, color:'lavender', image:SPORTS_MEDIA+'8cca422f5bb73a65b22fdd21fca38f3d029e86b1807aa30de69c2dcdffff7d17.jpeg', short:'Joyful bouncing that regulates, resets and delights.', intro:'Small, padded trampolines for rhythmic bouncing — a favourite for sensory regulation, body awareness and simple, happy movement.', focus:'Sensory input · regulation · rhythm', ages:'Suitable for ages 3–10 · individual & pairs', schedule:[['Monday & Friday','3:30 – 4:00 pm'],['Saturday','9:30 – 10:00 am']], goals:['Enjoying rhythmic, regulating movement','Building body and space awareness','Releasing energy in a calm way'], audience:'Children who seek movement and sensory input, or love to bounce and reset.'},
  {slug:'balance-agility', title:'Balance & Agility', icon:PersonStanding, color:'yellow', image:SPORTS_MEDIA+'4db80f89ac95df7386d79a69a5b2f6dec6b0b7759c5d693497b746633b39bb74.jpeg', short:'Soft beams and stepping stones for steady, growing confidence.', intro:'Gentle balance beams, stepping shapes and mini obstacle paths that invite focus, careful steps and a real sense of achievement.', focus:'Balance · focus · motor planning', ages:'Suitable for ages 4–11 · small groups', schedule:[['Tuesday','5:00 – 5:40 pm'],['Sunday','10:00 – 10:40 am']], goals:['Steadying balance and posture','Sequencing steps with focus','Moving through a path with confidence'], audience:'Children building balance, coordination and the confidence to try something new.'},
  {slug:'ball-games', title:'Playful Ball Games', icon:Dribbble, color:'sage', image:SPORTS_MEDIA+'d290bbcb2aa60e318a4b0496afc5d1e6f703f7e304d269ce07228363473b86d6.jpeg', short:'Rolling, catching and sharing — sport as a way to connect.', intro:'Soft-ball rolling, catching and cooperative games that make turn-taking, communication and shared fun the goal — not the score.', focus:'Turn-taking · communication · teamwork', ages:'Suitable for ages 5–12 · small groups', schedule:[['Thursday','5:00 – 5:45 pm'],['Saturday','12:00 – 12:45 pm']], goals:['Practising catching and rolling','Taking turns and sharing','Playing together, at everyone’s pace'], audience:'Children exploring social play, communication and cooperative movement.'},
  {slug:'movement-play', title:'Movement & Obstacle Play', icon:Waves, color:'peach', image:SPORTS_MEDIA+'188d0ba410981f01593aa4d47e74ed9b83bef9dcee63e4b3e31f4edacf265bff.jpeg', short:'Open-ended courses to crawl, climb, roll and explore.', intro:'Child-led obstacle courses with soft ramps, tunnels and shapes — space to move in whatever way feels good and follow your own idea of play.', focus:'Whole-body play · autonomy · joy', ages:'Suitable for ages 3–9 · drop-in & small groups', schedule:[['Monday – Friday','3:00 – 3:45 pm (drop-in)'],['Sunday','11:00 – 11:45 am']], goals:['Moving freely and creatively','Following a child-led idea','Exploring the whole body in motion'], audience:'Children who love open-ended, whole-body play with room to lead their own way.'},
];
export const concerns = [
  {name:'Communication', icon:MessageCircle, slugs:['speech-therapy','music-play-therapy'], sports:[]},
  {name:'Sensory needs', icon:Shapes, slugs:['sensory-integration-therapy','occupational-therapy'], sports:['trampoline-bounce']},
  {name:'Everyday skills', icon:Hand, slugs:['occupational-therapy'], sports:['balance-agility']},
  {name:'Learning', icon:BookOpen, slugs:['remedial-therapy'], sports:[]},
  {name:'Social participation', icon:Sprout, slugs:['music-play-therapy','speech-therapy'], sports:['ball-games']},
  {name:'Movement & play', icon:Footprints, slugs:[], sports:['roller-skating','soft-climbing','balance-agility','movement-play']},
  {name:'I’m not sure', icon:MessageCircle, slugs:[], sports:[]},
];
export const faqs = [
  ['Do I need a diagnosis before getting in touch?', 'You can contact the team without a diagnosis. Share your broad area of interest, and the team can explain the next steps. An enquiry or screening request is not a diagnosis.'],
  ['Does booking online confirm an appointment?', 'No. The form sends an assessment request. The team must contact you to discuss suitability, fees and availability before an appointment is confirmed.'],
  ['Can my child use gestures or a communication device?', 'Please tell the team about your child’s preferred ways of communicating, including speech, gestures, pictures or AAC. Support should respect those preferences.'],
  ['How much do sessions cost?', 'Fees, duration and payment policies must be confirmed by the center. You can request this information before deciding whether to proceed.'],
  ['Can parents be involved?', 'Family priorities and your child’s preferences are important to planning. Ask the team how shared goals, home activities and progress reviews could work for your family.'],
];